#!/usr/bin/env python3
"""Generate comprehensive Indonesian translation - Part 6: More long strings Q-Z."""

T6 = {
    # === Q-R long ===
    "Qualified players apply directly. Review their profiles, stats, and playstyle — then accept or pass. No more spamming transfer chat.": "Pemain yang memenuhi syarat melamar langsung. Tinjau profil, statistik, dan gaya bermain mereka — lalu terima atau lewati. Tidak perlu spam chat transfer lagi.",
    "Rate Kingdom {{num}}": "Nilai Kingdom {{num}}",
    "Reach Gold Tier through the Kingdom Fund to unlock this and other premium kingdom tools.": "Capai Gold Tier melalui Kingdom Fund untuk membuka ini dan alat kingdom premium lainnya.",
    "Reach Silver Tier ($50+) through the Kingdom Fund to unlock this and other premium kingdom tools.": "Capai Silver Tier ($50+) melalui Kingdom Fund untuk membuka ini dan alat kingdom premium lainnya.",
    "Real data. Real applications. No more guessing who's actually recruiting and who's worth joining.": "Data nyata. Lamaran nyata. Tidak perlu menebak lagi siapa yang benar-benar merekrut dan siapa yang layak diikuti.",
    "Real prizes for kingdoms with the most settlers. See campaign details →": "Hadiah nyata untuk kingdom dengan settler terbanyak. Lihat detail kampanye →",
    "Real-time summary of player availability and troop distribution. See your army composition at a glance — tier spread, truegold levels, alliance breakdown.": "Ringkasan real-time ketersediaan pemain dan distribusi pasukan. Lihat komposisi tentara Anda sekilas — sebaran tier, level truegold, rincian aliansi.",
    "Recruiting is a team effort. Anyone in your kingdom can chip in to boost the listing.": "Rekrutmen adalah usaha tim. Siapa pun di kingdom Anda bisa ikut kontribusi untuk meningkatkan daftar.",
    "Recruiting is a team effort. Anyone in your kingdom can chip in to boost the listing. Funds deplete slowly over time, so active kingdoms stay on top.": "Rekrutmen adalah usaha tim. Siapa pun di kingdom Anda bisa ikut kontribusi untuk meningkatkan daftar. Dana berkurang perlahan seiring waktu, jadi kingdom aktif tetap di atas.",
    "Redeem gift codes for all your alt accounts at once — one click": "Tukarkan kode hadiah untuk semua akun alt sekaligus — satu klik",
    "Register your availability and troop levels for the castle battle.": "Daftarkan ketersediaan dan level pasukan Anda untuk castle battle.",
    "Registries you've submitted your info to.": "Registrasi tempat Anda mengirimkan info.",
    "Relive the battles. Every matchup ranked by combined Atlas Score—see which kingdoms brought the heat.": "Hayati kembali pertempuran. Setiap pertandingan diranking berdasarkan Skor Atlas gabungan—lihat kingdom mana yang paling bersemangat.",
    "Remove {{name}}? This deletes all events, settings, and history for this server.": "Hapus {{name}}? Ini menghapus semua event, pengaturan, dan riwayat untuk server ini.",
    "Reopen the form for submissions?": "Buka kembali formulir untuk pengiriman?",
    "Report your availability and troop strength for KvK Castle Battles. Your kingdom needs to know who's showing up — and what they're bringing.": "Laporkan ketersediaan dan kekuatan pasukan Anda untuk KvK Castle Battle. Kingdom Anda perlu tahu siapa yang hadir — dan apa yang mereka bawa.",
    "Reports are reviewed by our team before updates are applied. Thank you for helping keep our data accurate!": "Laporan ditinjau oleh tim kami sebelum pembaruan diterapkan. Terima kasih telah membantu menjaga data kami tetap akurat!",
    "Request just sent! The editor has been notified.": "Permintaan baru dikirim! Editor telah diberitahu.",
    "Resource planners, upgrade costs, speedup estimates. Math so you don't have to.": "Perencana sumber daya, biaya upgrade, estimasi speedup. Matematika agar Anda tidak perlu.",

    # === S long ===
    "Search Kingdoms": "Cari Kingdom",
    "Search players...": "Cari pemain...",
    "Search by kingdom number or name...": "Cari berdasarkan nomor atau nama kingdom...",
    "Search...": "Cari...",
    "Select King's Castle or any of the 4 Turrets. Choose simultaneous or staggered hits.": "Pilih King's Castle atau salah satu dari 4 Menara. Pilih serangan simultan atau berurutan.",
    "Select the time range when you can be online for the castle battle.": "Pilih rentang waktu ketika Anda bisa online untuk castle battle.",
    "Select the time slot when you can be online for the castle battle. All times are in UTC.": "Pilih slot waktu ketika Anda bisa online untuk castle battle. Semua waktu dalam UTC.",
    "Send": "Kirim",
    "Share": "Bagikan",
    "Share your referral link and earn rewards!": "Bagikan tautan referral Anda dan dapatkan hadiah!",
    "Show Form": "Tampilkan Formulir",
    "Silver Tier Required": "Silver Tier Diperlukan",
    "Silver badge on listing": "Lencana Perak di daftar",
    "Simultaneous — all rallies land at the same time": "Simultan — semua rally mendarat bersamaan",
    "Skip": "Lewati",
    "Slot": "Slot",
    "Stagger": "Stagger",
    "Staggered — rallies land X seconds apart": "Berurutan — rally mendarat X detik terpisah",
    "Standard": "Standar",
    "Star": "Bintang",
    "Statistics": "Statistik",
    "Status": "Status",
    "Submit": "Kirim",
    "Submit KvK Result": "Kirim Hasil KvK",
    "Submitted": "Dikirim",
    "Submitted!": "Terkirim!",
    "Switch to \"I'm Recruiting\" and claim editor rights. You need endorsements from kingdom members to activate.": "Beralih ke \"Saya Merekrut\" dan klaim hak editor. Anda butuh dukungan dari anggota kingdom untuk mengaktifkan.",
    "Switch to another account before removing this one": "Ganti ke akun lain sebelum menghapus yang ini",
    "Synchronized destruction. No guesswork.": "Perusakan tersinkron. Tanpa tebak-tebakan.",

    # === T long ===
    "Tap \"Gift Code\" and paste the code": "Ketuk \"Gift Code\" dan tempel kodenya",
    "Tap Redeem": "Ketuk Tukar",
    "Tap Redeem — rewards appear in your mailbox": "Ketuk Tukar — hadiah muncul di kotak surat Anda",
    "TC Level {{level}}+ required to review (yours: {{current}})": "Level TC {{level}}+ diperlukan untuk ulasan (Anda: {{current}})",
    "TC20+ required to submit KvK results (you're TC{{level}}).": "TC20+ diperlukan untuk mengirim hasil KvK (Anda TC{{level}}).",
    "Thank you for supporting Atlas. Jump straight into the planner and coordinate your next castle hit.": "Terima kasih telah mendukung Atlas. Langsung masuk ke planner dan koordinasikan serangan castle Anda berikutnya.",
    "Thank you for supporting your kingdom's Transfer Hub listing. Your contribution helps the fund grow and unlocks better listing features.": "Terima kasih telah mendukung daftar Transfer Hub kingdom Anda. Kontribusi Anda membantu dana tumbuh dan membuka fitur daftar yang lebih baik.",
    "That's not planning. That's an architectural masterclass.": "Itu bukan sekadar perencanaan. Itu masterclass arsitektur.",
    "That's not scheduling. That's strategic resource allocation.": "Itu bukan sekadar penjadwalan. Itu alokasi sumber daya strategis.",
    "The ": "Fase ",
    "The 2-hour buff timer will be reset.": "Timer buff 2 jam akan direset.",
    "The Alliance Base Designer is available for Atlas Supporters, Ambassadors, and Discord Server Boosters. Become a Supporter to unlock this and other premium tools.": "Alliance Base Designer tersedia untuk Atlas Supporter, Ambassador, dan Discord Server Booster. Jadi Supporter untuk membuka ini dan alat premium lainnya.",
    "The Alliance Base Designer lets you plan the entire layout before anyone moves. Place every city, every trap, every building on the exact coordinates. Label each block with the player's name. Share the screenshot. Everyone knows exactly where to go. Need to adjust? It's drag and drop — rearrange the whole base in minutes, not hours.": "Alliance Base Designer memungkinkan Anda merencanakan seluruh tata letak sebelum siapa pun bergerak. Tempatkan setiap kota, setiap jebakan, setiap bangunan di koordinat yang tepat. Labeli setiap blok dengan nama pemain. Bagikan tangkapan layar. Semua tahu persis ke mana. Perlu menyesuaikan? Tinggal seret dan lepas — atur ulang seluruh base dalam menit, bukan jam.",
    "The Battle Planner accounts for the 5-minute rally fill time plus each player's individual march time, then tells you exactly who calls first and the precise delay between each call. Your rallies connect within a 1-second window. The enemy can't reinforce fast enough.": "Battle Planner memperhitungkan waktu pengisian rally 5 menit plus waktu march individu setiap pemain, lalu memberi tahu persis siapa yang memanggil duluan dan delay presisi antar panggilan. Rally Anda terhubung dalam jendela 1 detik. Musuh tidak bisa memperkuat cukup cepat.",
    "The Battle Planner is available for Gold Tier kingdoms. Help your kingdom reach Gold by contributing to the Kingdom Fund on the Transfer Hub.": "Battle Planner tersedia untuk kingdom Gold Tier. Bantu kingdom Anda mencapai Gold dengan berkontribusi ke Kingdom Fund di Transfer Hub.",
    "The Battle Planner is included with Atlas Supporter — along with unlimited /multirally, the Supporter badge, exclusive Discord access, and more. Starting at $4.99/month.": "Battle Planner termasuk dalam Atlas Supporter — bersama /multirally tak terbatas, lencana Supporter, akses Discord eksklusif, dan lainnya. Mulai dari $4.99/bulan.",
    "The Battle Registry collects every player's availability and troop levels in one place. You see exactly who can be online at 14:00 UTC, how many T11 cavalry your kingdom has, and which alliances are pulling their weight. Plan the battle with data — not hope.": "Battle Registry mengumpulkan ketersediaan dan level pasukan setiap pemain di satu tempat. Anda melihat persis siapa yang bisa online pukul 14:00 UTC, berapa banyak kavaleri T11 di kingdom Anda, dan aliansi mana yang berkontribusi. Rencanakan pertempuran dengan data — bukan harapan.",
    "The Battle Registry is available for Gold and Silver Tier kingdoms. Help your kingdom reach the tier by contributing to the Kingdom Fund.": "Battle Registry tersedia untuk kingdom Gold dan Silver Tier. Bantu kingdom Anda mencapai tier dengan berkontribusi ke Kingdom Fund.",
    "The KvK Battle Registry is available for Silver Tier ($50+) and Gold Tier ($100+) kingdoms. Contribute to the Kingdom Fund to reach Silver and unlock this tool!": "KvK Battle Registry tersedia untuk kingdom Silver Tier ($50+) dan Gold Tier ($100+). Kontribusi ke Kingdom Fund untuk mencapai Silver dan membuka alat ini!",
    "The KvK Prep Scheduler collects everything in one form — speedups, availability, proof screenshots — with a submission deadline shown in 24-hour UTC (and your local time). Then it auto-assigns slots based on who brings the most value for each day's buff type. Construction Monday? The system knows who has the most construction speedups and puts them in the best slots. Research Tuesday? Same logic, different data.": "Jadwal Prep KvK mengumpulkan semuanya dalam satu formulir — speedup, ketersediaan, tangkapan layar bukti — dengan tenggat pengiriman dalam UTC 24-jam (dan waktu lokal Anda). Lalu otomatis menetapkan slot berdasarkan siapa yang memberikan nilai terbaik untuk jenis buff setiap hari. Senin Konstruksi? Sistem tahu siapa yang punya speedup konstruksi terbanyak dan menempatkan mereka di slot terbaik. Selasa Riset? Logika sama, data berbeda.",
    "The KvK Prep Scheduler is available for Gold Tier kingdoms. Encourage your kingdom to reach Gold tier through the Kingdom Fund to unlock this tool!": "Jadwal Prep KvK tersedia untuk kingdom Gold Tier. Dorong kingdom Anda untuk mencapai Gold tier melalui Kingdom Fund untuk membuka alat ini!",
    "The KvK Prep Scheduler is available for Gold and Silver Tier kingdoms during the KvK #11 promotion. Contribute to the Kingdom Fund to reach Silver ($50+) or Gold ($100+) and unlock this tool!": "Jadwal Prep KvK tersedia untuk kingdom Gold dan Silver Tier selama promosi KvK #11. Kontribusi ke Kingdom Fund untuk mencapai Silver ($50+) atau Gold ($100+) dan membuka alat ini!",
    "The KvK Prep Scheduler is available to kingdoms with Silver Tier ($50+) or Gold Tier ($100+) status through the Kingdom Fund. If your kingdom isn't Silver Tier yet, encourage your alliance leaders to contribute.": "Jadwal Prep KvK tersedia untuk kingdom dengan status Silver Tier ($50+) atau Gold Tier ($100+) melalui Kingdom Fund. Jika kingdom Anda belum Silver Tier, dorong pemimpin aliansi untuk berkontribusi.",
    "The Prep Scheduler is available for Silver+ Tier kingdoms.": "Jadwal Prep tersedia untuk kingdom Silver+ Tier.",
    "The Transfer Hub gives you the data. Discord gives you the conversation. Use both to land in the right kingdom.": "Transfer Hub memberi Anda data. Discord memberi Anda percakapan. Gunakan keduanya untuk mendarat di kingdom yang tepat.",
    "The Transfer Hub replaces all of that. Every recruiting kingdom has real stats, an Atlas Score, KvK history, and community reviews. Players create profiles with their own stats and preferences. Apply directly. Track your applications. Done.": "Transfer Hub menggantikan semua itu. Setiap kingdom yang merekrut memiliki statistik nyata, Skor Atlas, riwayat KvK, dan ulasan komunitas. Pemain membuat profil dengan statistik dan preferensi mereka sendiri. Lamar langsung. Lacak lamaran Anda. Selesai.",
    "The Transfer Hub: No More Blind Transfers": "Transfer Hub: Tidak Ada Lagi Transfer Buta",
    "The algorithm prioritizes players with the highest relevant speedups for each day's buff type — Construction, Research, or Training. Every minute counts.": "Algoritma memprioritaskan pemain dengan speedup relevan tertinggi untuk jenis buff setiap hari — Konstruksi, Riset, atau Pelatihan. Setiap menit berharga.",
    "The better your Transfer Profile, the higher your Match Score with kingdoms. Fill it out completely — recruiters notice.": "Semakin baik Profil Transfer Anda, semakin tinggi Skor Kecocokan dengan kingdom. Isi dengan lengkap — perekrut memperhatikan.",
    "The big picture across {{count}} kingdoms. No spin.": "Gambaran besar dari {{count}} kingdom. Tanpa basa-basi.",
    "The castle is burning. Your rallies land 30 seconds apart.": "Castle sedang terbakar. Rally Anda mendarat 30 detik terpisah.",
    "The difference between a coordinated castle hit and wasted marches is timing. Get it right — every time.": "Perbedaan antara serangan castle terkoordinasi dan march yang sia-sia adalah timing. Lakukan dengan tepat — setiap saat.",
    "The founder got tired of making transfer decisions based on rumors and Discord hearsay. Tired of walking into KvK blind. Tired of guessing.": "Pendiri lelah membuat keputusan transfer berdasarkan rumor dan kabar burung Discord. Lelah memasuki KvK dengan buta. Lelah menebak.",
    "The kingdom fund balance is updated automatically": "Saldo dana kingdom diperbarui otomatis",
    "The more Settlers your kingdom has, the more raffle tickets you earn. Link your Discord and rally your kingdom!": "Semakin banyak Settler di kingdom Anda, semakin banyak tiket undian yang Anda dapatkan. Hubungkan Discord dan ajak kingdom Anda!",
    "The owner who registered this server. Only the owner can block/unblock users and remove the server.": "Pemilik yang mendaftarkan server ini. Hanya pemilik yang bisa memblokir/membuka blokir pengguna dan menghapus server.",
    "The planner calculates exact delays. Copy the call order and share it with your alliance.": "Planner menghitung delay tepat. Salin urutan panggilan dan bagikan dengan aliansi Anda.",
    "The players spreading data-driven dominance. More referrals, higher rank.": "Pemain yang menyebarkan dominasi berbasis data. Lebih banyak referral, peringkat lebih tinggi.",
    "The registration window has ended. View the registry to check the summary.": "Jendela registrasi telah berakhir. Lihat registrasi untuk memeriksa ringkasan.",
    "The sum of both kingdoms' Atlas Scores going into the matchup. Higher scores = more competitive battles between proven kingdoms. This is how legends are made.": "Jumlah Skor Atlas kedua kingdom yang memasuki pertandingan. Skor lebih tinggi = pertempuran lebih kompetitif antara kingdom terbukti. Begitulah legenda tercipta.",
    "These groups are from the last Transfer Event and may change before the next one.": "Grup-grup ini dari Transfer Event terakhir dan mungkin berubah sebelum yang berikutnya.",
    "These players have availability but weren't assigned a slot. You can manually assign them using the dropdowns below.": "Pemain-pemain ini punya ketersediaan tapi belum ditetapkan slot. Anda bisa menetapkan secara manual menggunakan dropdown di bawah.",
    "This Player ID is already linked to another Atlas account.": "ID Pemain ini sudah terhubung ke akun Atlas lain.",
    "This can happen on slow connections, mobile in-app browsers, or when switching apps during sign-in.": "Ini bisa terjadi pada koneksi lambat, browser in-app mobile, atau saat berpindah aplikasi selama masuk.",
    "This editor claim is no longer accepting endorsements.": "Klaim editor ini tidak lagi menerima dukungan.",
    "This endorsement link may be invalid or expired.": "Tautan dukungan ini mungkin tidak valid atau kadaluarsa.",
    "This is what kingdoms will see when reviewing your application": "Ini yang akan dilihat kingdom saat meninjau lamaran Anda",
}
