#!/usr/bin/env python3
"""Generate comprehensive Indonesian translation - Part 3: S-Z + long strings."""

T3 = {
    # === S ===
    "SEARCHING": "MENCARI",
    "Saved!": "Tersimpan!",
    "Schedule saved!": "Jadwal tersimpan!",
    "Submit Review": "Kirim Ulasan",
    "Submit a new kingdom not yet tracked in the Atlas. Select their first KvK to determine relevant history.": "Kirim kingdom baru yang belum dilacak di Atlas. Pilih KvK pertama mereka untuk menentukan riwayat yang relevan.",
    "Submitting for an alt account": "Mengirim untuk akun alt",
    "Support Atlas": "Dukung Atlas",
    "Support Atlas on Ko-fi": "Dukung Atlas di Ko-fi",
    "Supporter Badge — Stand out in the community": "Lencana Supporter — Tampil menonjol di komunitas",
    "Supporter · Ambassador · Booster": "Supporter · Ambassador · Booster",
    "Switch to Annual": "Beralih ke Tahunan",
    "Switching...": "Mengganti...",
    "Synced:": "Tersinkron:",
    "Synchronized destruction. No guesswork.": "Perusakan tersinkron. Tanpa tebak-tebakan.",

    # === T ===
    "TC (High)": "TC (Tinggi)",
    "TC Level": "Level TC",
    "TC Level (High → Low)": "Level TC (Tinggi → Rendah)",
    "TC Level 20+": "Level TC 20+",
    "TC Level 20+ required to become a co-editor.": "Level TC 20+ diperlukan untuk menjadi co-editor.",
    "TC Level 20+ required to endorse.": "Level TC 20+ diperlukan untuk mendukung.",
    "TIME SLOTS": "SLOT WAKTU",
    "Tactical tools built for players who coordinate to win.": "Alat taktis dibangun untuk pemain yang berkoordinasi untuk menang.",
    "Taking too long? Retry": "Terlalu lama? Coba lagi",
    "Tap a server to switch. Remove to disconnect completely.": "Ketuk server untuk mengganti. Hapus untuk memutuskan sepenuhnya.",
    "Tap players above to add": "Ketuk pemain di atas untuk menambah",
    "Tap to add to counter": "Ketuk untuk tambah ke counter",
    "Tap to add to rally": "Ketuk untuk tambah ke rally",
    "Tap to complete →": "Ketuk untuk menyelesaikan →",
    "Tell us what we could do better...": "Beritahu kami apa yang bisa kami perbaiki...",
    "The Fine Print": "Ketentuan Kecil",
    "This Week": "Minggu Ini",
    "This account is already linked": "Akun ini sudah terhubung",
    "This helps us personalize your experience": "Ini membantu kami mempersonalisasi pengalaman Anda",
    "Tier": "Tier",
    "Top 10% — Dominant": "Top 10% — Dominan",
    "Top 25% — Strong Contender": "Top 25% — Pesaing Kuat",
    "Top 50% — Competitive": "Top 50% — Kompetitif",
    "Troop Type": "Tipe Pasukan",
    "Truegold Level": "Level Truegold",

    # === U ===
    "UTC": "UTC",
    "Unlock the Planner": "Buka Planner",
    "Unread": "Belum Dibaca",
    "Update": "Perbarui",
    "Update Profile": "Perbarui Profil",
    "Updated!": "Diperbarui!",
    "Upgrade": "Upgrade",
    "Upload Screenshot": "Unggah Tangkapan Layar",
    "Uploading...": "Mengunggah...",
    "Username": "Username",

    # === V ===
    "Verified": "Terverifikasi",
    "View All": "Lihat Semua",
    "View Details": "Lihat Detail",
    "View Full Profile": "Lihat Profil Lengkap",
    "View Kingdom": "Lihat Kingdom",
    "View Profile": "Lihat Profil",
    "View Registry": "Lihat Registrasi",
    "Visibility": "Visibilitas",
    "Visible": "Terlihat",

    # === W ===
    "Waiting for players...": "Menunggu pemain...",
    "Waitlist": "Daftar Tunggu",
    "Warning": "Peringatan",
    "Wins": "Kemenangan",
    "Withdraw": "Tarik",
    "Withdraw Application": "Tarik Lamaran",

    # === Y ===
    "Year": "Tahun",
    "Yes, Cancel Subscription": "Ya, Batalkan Langganan",
    "You": "Anda",
    "Your Assigned Slots": "Slot Anda yang Ditetapkan",
    "Your Data is Safe": "Data Anda Aman",
    "Your Kingdom": "Kingdom Anda",
    "Your Prep Report": "Laporan Prep Anda",
    "Your Qualification Status": "Status Kualifikasi Anda",
    "Your Slots": "Slot Anda",
    "Your Submissions": "Pengiriman Anda",
    "Your Timezone": "Zona Waktu Anda",
    "Your Transfer Profile is Active": "Profil Transfer Anda Aktif",
    "Your choice is saved on this device. You can switch modes anytime.": "Pilihan Anda tersimpan di perangkat ini. Anda bisa ganti mode kapan saja.",
    "Your co-editor nomination has been cancelled.": "Nominasi co-editor Anda telah dibatalkan.",
    "Your feedback": "Masukan Anda",
    "Your in-game name": "Nama in-game Anda",
    "Your kingdom appears in transfer searches": "Kingdom Anda muncul di pencarian transfer",
    "Your kingdom could win real prizes. Rally your settlers!": "Kingdom Anda bisa memenangkan hadiah nyata. Ajak settler Anda!",
    "Your kingdom has an active prep schedule.": "Kingdom Anda memiliki jadwal prep aktif.",
    "Your kingdom is missing this KvK! Submit your results.": "Kingdom Anda kekurangan KvK ini! Kirim hasil Anda.",
    "Your payment is processed by Stripe": "Pembayaran Anda diproses oleh Stripe",
    "Your profile is hidden — recruiters cannot find or invite you": "Profil Anda tersembunyi — perekrut tidak bisa menemukan atau mengundang Anda",
    "Your response has been submitted": "Respons Anda telah dikirim",
    "Your server deserves better intel.": "Server Anda layak mendapat intelijen lebih baik.",
    "Your server, your rules. Configure everything from one place.": "Server Anda, aturan Anda. Konfigurasi semuanya dari satu tempat.",

    # === lowercase / short ===
    "account(s)": "akun",
    "available": "tersedia",
    "based on your Transfer Profile": "berdasarkan Profil Transfer Anda",
    "buildings": "bangunan",
    "change requests": "permintaan perubahan",
    "chars": "karakter",
    "currently": "saat ini",
    "d left": "h tersisa",
    "for": "untuk",
    "iOS Redemption": "Penukaran iOS",
    "iOS players must redeem via the Kingshot website due to App Store restrictions.": "Pemain iOS harus menukarkan melalui situs web Kingshot karena batasan App Store.",
    "kingdom page": "halaman kingdom",
    "kingdoms": "kingdom",
    "loaded": "dimuat",
    "match score available": "skor kecocokan tersedia",
    "min": "min",
    "more": "lebih",
    "needed": "dibutuhkan",
    "of": "dari",
    "of all kingdoms": "dari semua kingdom",
    "optional": "opsional",
    "optional override": "penggantian opsional",
    "pending": "tertunda",
    "per member": "per anggota",
    "pick up to": "pilih hingga",
    "player": "pemain",
    "read-only": "baca-saja",
    "registrations": "registrasi",
    "remaining": "tersisa",
    "s": "d",
    "selected": "dipilih",
    "skipped": "dilewati",
    "slots for": "slot untuk",
    "slots used": "slot terpakai",
    "submissions": "pengiriman",
    "tier changes": "perubahan tier",
    "to": "ke",
    "to coordinate your transfer.": "untuk mengkoordinasikan transfer Anda.",
    "to find recruiter contact info and coordinate your transfer.": "untuk menemukan info kontak perekrut dan mengkoordinasikan transfer Anda.",
    "to leave reviews": "untuk meninggalkan ulasan",
    "unassigned": "belum ditetapkan",
    "uncovered slots": "slot kosong",
    "user": "pengguna",
    "when cycle started": "saat siklus dimulai",
    "withdraw one to apply again": "tarik satu untuk melamar lagi",
    "← Back to Atlas Bot": "← Kembali ke Atlas Bot",
    "← Back to Tools": "← Kembali ke Alat",
    "↻ Refresh": "↻ Perbarui",
    "↻ Refresh List": "↻ Perbarui Daftar",
    "▲ Show Less": "▲ Tampilkan Lebih Sedikit",

    # === Emoji-prefixed ===
    "⚔️ Soldier Training": "⚔️ Pelatihan Prajurit",
    "⚠️ Appeal Decision": "⚠️ Banding Keputusan",
    "✅ Requirements": "✅ Persyaratan",
    "✓ Approve": "✓ Setujui",
    "✓ Copied!": "✓ Tersalin!",
    "✓ Endorsed": "✓ Didukung",
    "✓ Invited": "✓ Diundang",
    "✓ Link Copied!": "✓ Tautan Tersalin!",
    "✕ Decline": "✕ Tolak",
    "✨ Funded listings get shimmer borders, glow effects & more visibility": "✨ Daftar berdana mendapat batas berkilau, efek glow & visibilitas lebih",
    "🌐 Manage Multiple Servers": "🌐 Kelola Beberapa Server",
    "🌐 Multiple Servers": "🌐 Beberapa Server",
    "🎁 Gift Codes": "🎁 Kode Hadiah",
    "🏗️ Construction": "🏗️ Konstruksi",
    "👁️ Visible to Recruiters": "👁️ Terlihat oleh Perekrut",
    "💡 How It Works": "💡 Cara Kerja",
    "📅 Event Calendar": "📅 Kalender Event",
    "📩 Send Invite": "📩 Kirim Undangan",
    "🔗 Copy Link": "🔗 Salin Tautan",
    "🔗 Refer a Friend": "🔗 Referensikan Teman",
    "🔬 Research": "🔬 Riset",
    "🙈 Hidden from Recruiters": "🙈 Tersembunyi dari Perekrut",
    "🧭 Navigate": "🧭 Navigasi",
    "🧱 Buildings": "🧱 Bangunan",

    # === Arrow symbols ===
    "→ {{tier}} tier": "→ tier {{tier}}",
    "— tap to learn": "— ketuk untuk mempelajari",
    "≈ = estimated (×1.55 ratio). Enter both to use exact values.": "≈ = estimasi (rasio ×1.55). Masukkan keduanya untuk nilai yang tepat.",
}
