#!/usr/bin/env python3
"""Generate comprehensive Indonesian translation - Part 7: More T-Z + remaining strings."""

T7 = {
    # === T-Y remaining long strings ===
    "This kingdom is not currently recruiting. Check back later or browse other kingdoms.": "Kingdom ini saat ini tidak merekrut. Periksa kembali nanti atau jelajahi kingdom lainnya.",
    "This kingdom's fund has reached {{tier}} tier! Thank you for supporting your kingdom.": "Dana kingdom ini telah mencapai tier {{tier}}! Terima kasih telah mendukung kingdom Anda.",
    "This Player ID is already linked to another Atlas account.": "ID Pemain ini sudah terhubung ke akun Atlas lain.",
    "Together, those adjustments give a single number that captures experience, consistency, streaks, and clutch factor. That's the Atlas Score.": "Bersama-sama, penyesuaian tersebut memberikan satu angka yang menangkap pengalaman, konsistensi, streak, dan faktor clutch. Itulah Skor Atlas.",
    "Track all your applications in one place": "Lacak semua lamaran Anda di satu tempat",
    "Transfer Event #{{num}}": "Transfer Event #{{num}}",
    "Transfer Hub": "Transfer Hub",
    "Transfer Hub — Find Your Next Kingdom": "Transfer Hub — Temukan Kingdom Berikutnya",
    "Transfer Profile": "Profil Transfer",
    "Transferring to a new kingdom is the biggest decision in Kingshot. You leave your alliance, your territory, your progress behind — all based on a pitch from someone you've never met. Is the kingdom actually good? Do they win KvK? Are the recruiters legit. You end up asking in Discord and getting 20 different opinions.": "Transfer ke kingdom baru adalah keputusan terbesar di Kingshot. Anda meninggalkan aliansi, wilayah, progres Anda — semua berdasarkan pitch dari seseorang yang belum pernah Anda temui. Apakah kingdom-nya benar-benar bagus? Apakah mereka menang KvK? Apakah perekrutnya legit. Akhirnya Anda bertanya di Discord dan mendapat 20 pendapat berbeda.",
    "Unlink": "Putuskan",
    "Unlink Discord": "Putuskan Discord",
    "Updating...": "Memperbarui...",
    "Use the player form to submit your own registration:": "Gunakan formulir pemain untuk mengirim registrasi Anda sendiri:",

    "View submitted registrations and player data.": "Lihat registrasi yang dikirim dan data pemain.",
    "We obsess over accuracy, but KvK is complex—edge cases exist. If you spot an error, let us know.": "Kami terobsesi dengan akurasi, tapi KvK itu kompleks—kasus tepi ada. Jika Anda menemukan kesalahan, beri tahu kami.",

    "When your kingdom has an active Battle Registry, it will appear here. Ask your leadership to share the form link.": "Saat kingdom Anda memiliki Battle Registry aktif, akan muncul di sini. Minta kepemimpinan untuk membagikan tautan formulir.",
    "Who are you?": "Siapa Anda?",

    "You can only apply to kingdoms that are actively recruiting.": "Anda hanya bisa melamar ke kingdom yang aktif merekrut.",
    "You have already reviewed this kingdom": "Anda sudah mengulas kingdom ini",
    "You must be logged in to access this feature.": "Anda harus masuk untuk mengakses fitur ini.",
    "You need to be logged in to access the Battle Registry. Sign in with Discord to continue.": "Anda harus masuk untuk mengakses Battle Registry. Masuk dengan Discord untuk melanjutkan.",
    "You need to create a transfer profile before you can apply to kingdoms. Your profile tells recruiters about you.": "Anda perlu membuat profil transfer sebelum bisa melamar ke kingdom. Profil Anda memberitahu perekrut tentang Anda.",
    "You need to link your Kingshot account before creating a transfer profile. This ensures your kingdom and TC level are verified.": "Anda perlu menghubungkan akun Kingshot sebelum membuat profil transfer. Ini memastikan kingdom dan level TC Anda terverifikasi.",
    "You need to link your Kingshot player profile before registering. Go to your Profile to link your account.": "Anda perlu menghubungkan profil pemain Kingshot sebelum mendaftar. Buka Profil untuk menghubungkan akun.",
    "You post in kingdom chat. Half the alliances don't reply. You get a rough count an hour before the battle. Some people show up with T5 infantry when you needed T11 cavalry. The castle falls because you didn't know what you had.": "Anda posting di chat kingdom. Setengah aliansi tidak membalas. Anda mendapat hitungan kasar satu jam sebelum pertempuran. Beberapa orang muncul dengan infanteri T5 padahal Anda butuh kavaleri T11. Castle jatuh karena Anda tidak tahu apa yang dimiliki.",
    "You'll be redirected after submitting": "Anda akan dialihkan setelah mengirim",
    "You're qualified! Your ticket counts for your kingdom.": "Anda memenuhi syarat! Tiket Anda dihitung untuk kingdom Anda.",
    "You're saving with yearly billing": "Anda berhemat dengan tagihan tahunan",
    "You've already reviewed this kingdom": "Anda sudah mengulas kingdom ini",
    "You've been invited to be a co-editor for Kingdom {{kingdom}}'s recruiter dashboard.": "Anda diundang menjadi co-editor untuk dasbor perekrut Kingdom {{kingdom}}.",
    "You've been invited to co-edit Kingdom {{kingdom}}'s recruiter dashboard.": "Anda diundang untuk co-edit dasbor perekrut Kingdom {{kingdom}}.",
    "You've got 5 rally callers. Different march times. Someone calls too early, someone too late. The enemy reinforces between hits. Sound familiar?": "Anda punya 5 pemanggil rally. Waktu march berbeda. Seseorang memanggil terlalu awal, seseorang terlalu lambat. Musuh memperkuat di antara serangan. Terdengar familiar?",
    "You've used all 3 application slots. Withdraw an existing application to apply here.": "Anda telah menggunakan semua 3 slot lamaran. Tarik lamaran yang ada untuk melamar di sini.",
    "Your Silver+ Tier kingdom earned elite tools. Stop losing Prep Phase points to disorganized buff scheduling — Atlas turns chaos into a precision-timed machine that maximizes every 30-minute slot.": "Kingdom Silver+ Tier Anda mendapatkan alat elite. Berhenti kehilangan poin Fase Prep karena penjadwalan buff yang tidak terorganisir — Atlas mengubah kekacauan menjadi mesin presisi yang memaksimalkan setiap slot 30 menit.",
    "Your alliance base is a fortress — or a liability. Plan the layout before a single flag drops. No more \"just put your city anywhere.\"": "Base aliansi Anda adalah benteng — atau kewajiban. Rencanakan tata letak sebelum satu bendera pun jatuh. Tidak ada lagi \"taruh kota di mana saja.\"",
    "Your alliance deserves a real battle plan.": "Aliansi Anda layak mendapat rencana pertempuran nyata.",
    "Your command center. Configure reminders, gift code alerts, and manage multiple servers — all from one screen.": "Pusat komando Anda. Konfigurasi pengingat, peringatan kode hadiah, dan kelola beberapa server — semua dari satu layar.",
    "Your fund balance dropped below the {{tier}} tier threshold. You have {{days}} day(s) to top up before your tier is reduced. Share the contribution link with your kingdom!": "Saldo dana Anda turun di bawah ambang tier {{tier}}. Anda punya {{days}} hari untuk mengisi ulang sebelum tier Anda diturunkan. Bagikan tautan kontribusi dengan kingdom Anda!",
    "Your kingdom deserves organized prep phases.": "Kingdom Anda layak mendapat fase prep yang terorganisir.",
    "Your kingdom has 200 players. 48 buff slots per day. Do the math.": "Kingdom Anda punya 200 pemain. 48 slot buff per hari. Hitung sendiri.",
    "Your kingdom has earned Gold Tier status. Jump straight into the planner and coordinate your next castle hit.": "Kingdom Anda telah mendapat status Gold Tier. Langsung masuk ke planner dan koordinasikan serangan castle berikutnya.",
    "Your kingdom has earned access. Create a registry and start collecting player intel for your next castle battle.": "Kingdom Anda telah mendapat akses. Buat registrasi dan mulai kumpulkan intel pemain untuk castle battle berikutnya.",
    "Your kingdom needs Gold Tier to use the Prep Scheduler.": "Kingdom Anda memerlukan Gold Tier untuk menggunakan Jadwal Prep.",
    "Your kingdom needs at least 10 qualifying Settlers to enter": "Kingdom Anda memerlukan setidaknya 10 Settler yang memenuhi syarat untuk masuk",
    "Your kingdom's Prep Phase doesn't have to be chaos. The Scheduler turns it into a streamlined, data-driven process.": "Fase Prep kingdom Anda tidak harus kacau. Penjadwal mengubahnya menjadi proses yang efisien dan berbasis data.",
    "Your layout auto-saves to your browser. Refresh the page, come back tomorrow — your design is still there. Save multiple designs too.": "Tata letak Anda otomatis tersimpan di browser. Refresh halaman, kembali besok — desain Anda masih ada. Simpan beberapa desain juga.",
    "Your request to co-edit Kingdom {{kingdom}} is pending editor approval. You'll be notified when it's reviewed.": "Permintaan Anda untuk co-edit Kingdom {{kingdom}} menunggu persetujuan editor. Anda akan diberitahu saat ditinjau.",
    "Your sign-in session was lost during the Discord redirect. This commonly happens on mobile devices.": "Sesi masuk Anda hilang selama pengalihan Discord. Ini biasa terjadi di perangkat mobile.",
    "Your speedups don't meet the minimum threshold for any prep day. Your submission is saved but you may be placed on the waitlist.": "Speedup Anda tidak memenuhi ambang minimum untuk hari prep mana pun. Pengiriman Anda tersimpan tapi Anda mungkin ditempatkan di daftar tunggu.",
    "Your transfer profile will be shared with Kingdom {{kingdom}}'s recruiters. Applications expire after 72 hours if not responded to.": "Profil transfer Anda akan dibagikan dengan perekrut Kingdom {{kingdom}}. Lamaran kadaluarsa setelah 72 jam jika tidak direspons.",
    "Your username and kingdom will be hidden from recruiters until you reveal them.": "Username dan kingdom Anda akan disembunyikan dari perekrut sampai Anda mengungkapkannya.",
    "Your Prep Manager has not assigned you a slot yet. Check back later or contact your Prep Manager.": "Manajer Prep Anda belum menetapkan slot untuk Anda. Periksa kembali nanti atau hubungi Manajer Prep Anda.",

    # === Parameterized/dynamic strings ===
    "\"Am I climbing or slipping?\"": "\"Apakah saya naik atau turun?\"",
    "\"How do I reach the next tier?\"": "\"Bagaimana cara mencapai tier berikutnya?\"",
    "\"How has my score evolved?\"": "\"Bagaimana skor saya berkembang?\"",
    "\"How many people do we have for castle?\" — Every R5, every KvK.": "\"Berapa banyak orang yang kita punya untuk castle?\" — Setiap R5, setiap KvK.",
    "\"Just put your city near the flag.\" That's not a strategy.": "\"Taruh kota di dekat bendera.\" Itu bukan strategi.",
    "\"What if I win the next KvK?\"": "\"Bagaimana kalau saya menang KvK berikutnya?\"",
    "\"What's my win rate trend?\"": "\"Bagaimana tren win rate saya?\"",
    "\"Why is my score what it is?\"": "\"Mengapa skor saya seperti ini?\"",
    "\"{{name}}\" saved successfully.": "\"{{name}}\" berhasil disimpan.",
    "\"{{name}}\" updated successfully.": "\"{{name}}\" berhasil diperbarui.",
    "(Server Settings → Roles → drag Atlas Bot higher)": "(Server Settings → Roles → seret Atlas Bot lebih tinggi)",
    "({{count}} kingdom)": "({{count}} kingdom)",
    "({{count}} kingdoms)": "({{count}} kingdom)",
    "({{count}}/{{max}} co-editor slots used)": "({{count}}/{{max}} slot co-editor terpakai)",
    "+ Gilded badge · battle planner · battle registry · priority": "+ Lencana emas · battle planner · battle registry · prioritas",
    "+ Invites · prep scheduler": "+ Undangan · jadwal prep",
    "+ {{count}} more transactions": "+ {{count}} transaksi lagi",
    "+2 alliance slots (5 total)": "+2 slot aliansi (5 total)",
    "+{{count}} more": "+{{count}} lagi",
    "10 Referrals": "10 Referral",
    "10 endorsements from TC20+ kingdom members (after nomination)": "10 dukungan dari anggota kingdom TC20+ (setelah nominasi)",
    "10+ Discord servers": "10+ server Discord",
    "15 Prizes — Drawn Smallest to Largest": "15 Hadiah — Diundi dari Terkecil ke Terbesar",
    "2 Referrals": "2 Referral",
    "20 Referrals": "20 Referral",
    "20 regular invites, 10 open slots, lower power cap": "20 undangan reguler, 10 slot terbuka, batas kekuatan rendah",
    "35 regular invites, up to 3 special invites, 20 open slots, higher power cap": "35 undangan reguler, hingga 3 undangan spesial, 20 slot terbuka, batas kekuatan tinggi",
    "5 Referrals": "5 Referral",
    "5 bonus invites per cycle": "5 undangan bonus per siklus",
    "5 free uses per day": "5 penggunaan gratis per hari",
    " phase is active now.": " fase aktif sekarang.",

    # === More template strings ===
    "{{count}} Discord servers": "{{count}} server Discord",
    "{{count}} domination(s) needed": "{{count}} dominasi dibutuhkan",
    "{{count}} item(s) expiring within 24 hours": "{{count}} item kadaluarsa dalam 24 jam",
    "{{count}} kingdom(s) viewed your profile": "{{count}} kingdom melihat profil Anda",
    "{{count}} kingdoms": "{{count}} kingdom",
    "{{count}} message(s) waiting to send": "{{count}} pesan menunggu untuk dikirim",
    "{{count}} missing": "{{count}} hilang",
    "{{count}} more review(s) needed for Google rating badge": "{{count}} ulasan lagi dibutuhkan untuk lencana rating Google",
    "{{count}} more to unlock": "{{count}} lagi untuk membuka",
    "{{count}} players joined via referrals this month": "{{count}} pemain bergabung melalui referral bulan ini",
    "{{count}} queued message(s) sent": "{{count}} pesan antrean terkirim",
    "{{count}} review": "{{count}} ulasan",
    "{{count}} review(s)": "{{count}} ulasan",
    "{{count}} selected for comparison": "{{count}} dipilih untuk perbandingan",
    "{{count}}-Kingdom Performance Comparison": "Perbandingan Performa {{count}} Kingdom",
    "{{count}}/3 application slots used": "{{count}}/3 slot lamaran terpakai",
    "{{days}}d left": "{{days}}h tersisa",
    "{{days}}d {{hours}}h left": "{{days}}h {{hours}}j tersisa",
    "{{day}} disabled.": "{{day}} dinonaktifkan.",
    "{{day}} enabled.": "{{day}} diaktifkan.",
    "{{hours}}h {{mins}}m left": "{{hours}}j {{mins}}m tersisa",
    "{{inviter}} invited you to co-edit Kingdom {{kingdom}}'s recruiter dashboard.": "{{inviter}} mengundang Anda untuk co-edit dasbor perekrut Kingdom {{kingdom}}.",
    "{{kingdoms}} kingdoms · {{players}} verified players": "{{kingdoms}} kingdom · {{players}} pemain terverifikasi",
    "{{mins}}m left": "{{mins}}m tersisa",
    "{{name}} is now the editor of Kingdom {{num}}.": "{{name}} sekarang menjadi editor Kingdom {{num}}.",
    "{{score}}% match": "{{score}}% kecocokan",
    "{{tier}} TIER BENEFITS": "KEUNTUNGAN TIER {{tier}}",
    "{{username}} added as Battle Manager.": "{{username}} ditambahkan sebagai Battle Manager.",
    "{{username}} added as Prep Manager.": "{{username}} ditambahkan sebagai Manajer Prep.",
    "{{username}} removed from slot.": "{{username}} dihapus dari slot.",
    "All {{count}} Codes Copied": "Semua {{count}} Kode Tersalin",
    "All {{day}} assignments cleared.": "Semua penugasan {{day}} dihapus.",
    "Attempt {{count}} of {{max}} · Rechecking every {{seconds}}s": "Percobaan {{count}} dari {{max}} · Memeriksa ulang setiap {{seconds}}d",
    "Access expires in {{days}}d {{hours}}h.": "Akses berakhir dalam {{days}}h {{hours}}j.",
    "Access expires in {{days}}d {{hours}}h. Reach Silver tier to keep permanent access.": "Akses berakhir dalam {{days}}h {{hours}}j. Capai tier Silver untuk akses permanen.",
    "Access expires in {{hours}}h.": "Akses berakhir dalam {{hours}}j.",
    "Access expires in {{hours}}h. Reach Silver tier to keep permanent access.": "Akses berakhir dalam {{hours}}j. Capai tier Silver untuk akses permanen.",
    "Access granted by {{name}}": "Akses diberikan oleh {{name}}",
    "Access to supporter-only discussions and early previews": "Akses ke diskusi khusus supporter dan pratinjau awal",
    "Account added: {{name}} (K{{kingdom}})": "Akun ditambahkan: {{name}} (K{{kingdom}})",
    "Account linked: {{name}}": "Akun terhubung: {{name}}",
    "Account removed": "Akun dihapus",
    "Add KvK {{num}} Matchup": "Tambah Pertandingan KvK {{num}}",
    "Add a registration entry for a player who hasn't registered in Atlas. This entry will be marked as manually added.": "Tambah entri registrasi untuk pemain yang belum mendaftar di Atlas. Entri ini akan ditandai sebagai tambahan manual.",
    "Atlas Users from Kingdom {{num}}": "Pengguna Atlas dari Kingdom {{num}}",
    "Brief review, max 200 characters...": "Ulasan singkat, maks 200 karakter...",
    "Browse all Kingdom {{num}} players →": "Jelajahi semua pemain Kingdom {{num}} →",
    "Castle Battle hasn't ended yet. Unlocks {{date}}.": "Castle Battle belum berakhir. Terbuka {{date}}.",
    "Copied {{code}}": "Tersalin {{code}}",
    "Copied {{count}} codes to clipboard": "Tersalin {{count}} kode ke clipboard",
    "Corrections to Submit ({{count}})": "Koreksi untuk Dikirim ({{count}})",
    "Switched to {{name}} (K{{kingdom}})": "Beralih ke {{name}} (K{{kingdom}})",
    "Ownership verified! Account added: {{name}} (K{{kingdom}})": "Kepemilikan terverifikasi! Akun ditambahkan: {{name}} (K{{kingdom}})",
    "Notify {{count}} unsubmitted players via Discord DM that the deadline is approaching. Players must have Discord linked.": "Beritahu {{count}} pemain yang belum mengirim melalui DM Discord bahwa tenggat waktu mendekat. Pemain harus memiliki Discord terhubung.",
    "▼ View All {{count}} Favorite": "▼ Lihat Semua {{count}} Favorit",
    "▼ View All {{count}} Favorites": "▼ Lihat Semua {{count}} Favorit",
    "▼ View All {{count}} Reviews": "▼ Lihat Semua {{count}} Ulasan",
    "▼ View {{count}} Review": "▼ Lihat {{count}} Ulasan",
    "📊 Submit KvK #{{num}} Result": "📊 Kirim Hasil KvK #{{num}}",
    "⚠️ KvK #{{num}} data missing": "⚠️ Data KvK #{{num}} hilang",
    "e.g., 'The opponent was actually Kingdom 245' or 'We won the Battle phase, not lost'": "mis., 'Lawan sebenarnya Kingdom 245' atau 'Kami menang fase Battle, bukan kalah'",
    "for compiling the original KvK History spreadsheet that made this project possible. Community effort at its finest.": "karena menyusun spreadsheet Riwayat KvK asli yang membuat proyek ini mungkin. Upaya komunitas terbaiknya.",
    "for rallying this idea into existence. Built by the community, for the community.": "karena menggalang ide ini menjadi kenyataan. Dibangun oleh komunitas, untuk komunitas.",
    "puts real data behind the biggest decision in Kingshot.": "menempatkan data nyata di balik keputusan terbesar di Kingshot.",
    "requires Atlas {{tier}}": "memerlukan Atlas {{tier}}",
    "Our data comes from community contributions and verified KvK results. We obsess over accuracy, but KvK is complex—edge cases exist. If you spot an error, let us know.": "Data kami berasal dari kontribusi komunitas dan hasil KvK terverifikasi. Kami terobsesi dengan akurasi, tapi KvK itu kompleks—kasus tepi ada. Jika Anda menemukan kesalahan, beri tahu kami.",
    "Our formula rewards experience, punishes lucky streaks, and shows who really dominates. Here's the breakdown:": "Rumus kami menghargai pengalaman, menghukum streak beruntung, dan menunjukkan siapa yang benar-benar mendominasi. Berikut rinciannya:",
}
