#!/usr/bin/env python3
"""Generate comprehensive Indonesian translation - Part 5: More long strings F-P."""

T5 = {
    # === F long strings ===
    "Failed to add account": "Gagal menambah akun",
    "Failed to add delegate": "Gagal menambah delegasi",
    "Failed to add manager.": "Gagal menambah manajer.",
    "Failed to add manual entry.": "Gagal menambah entri manual.",
    "Failed to archive schedule.": "Gagal mengarsipkan jadwal.",
    "Failed to assign slot.": "Gagal menetapkan slot.",
    "Failed to clear assignments.": "Gagal menghapus penugasan.",
    "Failed to create registry.": "Gagal membuat registrasi.",
    "Failed to create schedule.": "Gagal membuat jadwal.",
    "Failed to delete entry.": "Gagal menghapus entri.",
    "Failed to delete schedule.": "Gagal menghapus jadwal.",
    "Failed to load kingdom data. Please try again later.": "Gagal memuat data kingdom. Silakan coba lagi nanti.",
    "Failed to process co-editor request.": "Gagal memproses permintaan co-editor.",
    "Failed to refresh data": "Gagal memperbarui data",
    "Failed to remove assignment. You may not have permission.": "Gagal menghapus penugasan. Anda mungkin tidak memiliki izin.",
    "Failed to remove delegate": "Gagal menghapus delegasi",
    "Failed to save profile: {{error}}": "Gagal menyimpan profil: {{error}}",
    "Failed to send notifications.": "Gagal mengirim notifikasi.",
    "Failed to sign in. Please try again or check your connection.": "Gagal masuk. Silakan coba lagi atau periksa koneksi Anda.",
    "Failed to start checkout. Please try again.": "Gagal memulai checkout. Silakan coba lagi.",
    "Failed to start sign-in. Please try again.": "Gagal memulai masuk. Silakan coba lagi.",
    "Failed to submit registration.": "Gagal mengirim registrasi.",
    "Failed to submit request.": "Gagal mengirim permintaan.",
    "Failed to switch account": "Gagal mengganti akun",
    "Failed to toggle stagger.": "Gagal mengubah stagger.",
    "Failed to unlink Discord": "Gagal memutus Discord",
    "Failed to update day settings.": "Gagal memperbarui pengaturan hari.",
    "Failed to update deadline": "Gagal memperbarui tenggat waktu",
    "Failed to update lock status.": "Gagal memperbarui status kunci.",
    "Failed to update opt-outs.": "Gagal memperbarui opt-out.",
    "Failed to update player entry.": "Gagal memperbarui entri pemain.",
    "Failed to update status.": "Gagal memperbarui status.",
    "Failed to update submission.": "Gagal memperbarui pengiriman.",
    "Failed: {{error}}": "Gagal: {{error}}",
    "Fill out the form. Submit speedups, availability, and proof. Get assigned a 30-minute slot. Show up and buff.": "Isi formulir. Kirim speedup, ketersediaan, dan bukti. Dapatkan slot 30 menit. Hadir dan buff.",
    "Find the perfect kingdom for you. No more blind transfers.": "Temukan kingdom sempurna untuk Anda. Tidak ada lagi transfer buta.",

    # === G-H long ===
    "Gold badge on listing": "Lencana Emas di daftar",
    "Hide Form": "Sembunyikan Formulir",
    "Hide Manual Add": "Sembunyikan Tambah Manual",

    # === I long ===
    "I confirm these screenshots are my own in-game captures. I understand that all game content depicted is the property of Century Games, and I grant Kingshot Atlas permission to store and display them for community data purposes.": "Saya mengonfirmasi tangkapan layar ini adalah milik saya dari in-game. Saya memahami bahwa semua konten game yang ditampilkan adalah milik Century Games, dan saya memberikan izin kepada Kingshot Atlas untuk menyimpan dan menampilkannya untuk tujuan data komunitas.",
    "If the fund reaches a new tier, the listing upgrades": "Jika dana mencapai tier baru, daftar akan upgrade",
    "Interested in Kingdom {{num}}?": "Tertarik dengan Kingdom {{num}}?",
    "Invalid time range. \"To\" must be equal to or after \"From\".": "Rentang waktu tidak valid. \"Sampai\" harus sama dengan atau setelah \"Dari\".",
    "Is this your account? Click \"Link Account\" to connect it to your Atlas profile.": "Apakah ini akun Anda? Klik \"Hubungkan Akun\" untuk menghubungkannya ke profil Atlas Anda.",

    # === J-K long ===
    "Join the Kingshot Atlas Discord server to get the Settler role": "Gabung server Discord Kingshot Atlas untuk mendapatkan peran Settler",
    "Joined Atlas Discord (Settler role)": "Bergabung dengan Atlas Discord (peran Settler)",
    "K-{{num}} not found in database": "K-{{num}} tidak ditemukan di database",
    "Kingdom data is fetched from our database. If this persists, please try again later.": "Data kingdom diambil dari database kami. Jika berlanjut, silakan coba lagi nanti.",
    "Kingdom editors can see your profile and send invites": "Editor kingdom bisa melihat profil Anda dan mengirim undangan",
    "Kingdom intel straight in your Discord server": "Intelijen kingdom langsung di server Discord Anda",
    "Kingdom intelligence, delivered straight to your Discord server. No tab-switching. No delays. Just data.": "Intelijen kingdom, dikirim langsung ke server Discord Anda. Tanpa ganti tab. Tanpa delay. Hanya data.",
    "Kingdom {{kingdom}} already has an editor. Join as a co-editor to help manage the Transfer Hub listing.": "Kingdom {{kingdom}} sudah memiliki editor. Bergabung sebagai co-editor untuk membantu mengelola daftar Transfer Hub.",
    "Kingdom {{kingdom}} does not have Gold or Silver tier. Only qualifying kingdoms can use this tool.": "Kingdom {{kingdom}} tidak memiliki tier Gold atau Silver. Hanya kingdom yang memenuhi syarat yang bisa menggunakan alat ini.",
    "Kingdom {{kingdom}} does not have Silver or Gold tier.": "Kingdom {{kingdom}} tidak memiliki tier Silver atau Gold.",
    "Kingdom {{kingdom}} has {{count}} active registry(ies). Submit your availability and troop info so your leadership can plan the castle hit.": "Kingdom {{kingdom}} memiliki {{count}} registrasi aktif. Kirim ketersediaan dan info pasukan Anda agar kepemimpinan bisa merencanakan serangan castle.",
    "Kingdom {{number}} data updated": "Data Kingdom {{number}} diperbarui",
    "Kingdoms can see your profile when you apply. You can edit it anytime.": "Kingdom bisa melihat profil Anda saat Anda melamar. Anda bisa mengeditnya kapan saja.",
    "Kingdoms fund their listing to unlock better visibility and features.": "Kingdom mendanai daftar mereka untuk membuka visibilitas dan fitur yang lebih baik.",
    "Kingdoms with active funds rank higher in listings. Even a Bronze tier gets you noticed over Standard listings.": "Kingdom dengan dana aktif mendapat peringkat lebih tinggi di daftar. Bahkan tier Perunggu membuat Anda lebih terlihat dari daftar Standar.",
    "Kingshot Atlas is an independent fan project. We're not affiliated with or endorsed by the developers of Kingshot. We're just players who love the game.": "Kingshot Atlas adalah proyek penggemar independen. Kami tidak berafiliasi dengan atau didukung oleh pengembang Kingshot. Kami hanyalah pemain yang mencintai game ini.",
    "Kingshot Atlas was born in": "Kingshot Atlas lahir pada",
    "Kingshot is a trademark of Century Games. All game content and materials are trademarks and copyrights of Century Games and its licensors. Kingshot Atlas is not affiliated with, endorsed, sponsored, or approved by Century Games. All KvK data on this platform is community-sourced and user-submitted.": "Kingshot adalah merek dagang Century Games. Semua konten dan materi game adalah merek dagang dan hak cipta Century Games dan pemberi lisensinya. Kingshot Atlas tidak berafiliasi dengan, didukung, disponsori, atau disetujui oleh Century Games. Semua data KvK di platform ini bersumber dari komunitas dan dikirim pengguna.",
    "Kingshot™ is a trademark of Century Games. All game content and materials are trademarks and copyrights of their respective owners. Kingshot Atlas is an independent fan project — not affiliated with, endorsed, sponsored, or approved by Century Games.": "Kingshot™ adalah merek dagang Century Games. Semua konten dan materi game adalah merek dagang dan hak cipta pemilik masing-masing. Kingshot Atlas adalah proyek penggemar independen — tidak berafiliasi dengan, didukung, disponsori, atau disetujui oleh Century Games.",
    "Kingshot linked (TC {{level}}+)": "Kingshot terhubung (TC {{level}}+)",
    "Kingshot players across dozens of servers use Atlas Bot to scout opponents, compare kingdoms, and plan transfers — without leaving Discord.": "Pemain Kingshot di puluhan server menggunakan Atlas Bot untuk mengintai lawan, membandingkan kingdom, dan merencanakan transfer — tanpa meninggalkan Discord.",
    "Know someone here? Invite them — every referral counts toward your Ambassador rank.": "Kenal seseorang di sini? Undang mereka — setiap referral berkontribusi pada peringkat Ambassador Anda.",
    "Know this kingdom's KvK result? Help complete the data.": "Tahu hasil KvK kingdom ini? Bantu lengkapi datanya.",
    "KvK #{{kvk}} — Register your availability and troop levels for the castle battle.": "KvK #{{kvk}} — Daftarkan ketersediaan dan level pasukan Anda untuk castle battle.",
    "K{{kingdom}} KvK #{{kvk}} data corrected": "Data K{{kingdom}} KvK #{{kvk}} dikoreksi",

    # === L long ===
    "Last 5 KvKs weighted by recency. Domination=1.0, Comeback=0.80, Reversal=0.70, Invasion=0.": "5 KvK terakhir berbobot berdasarkan kebaruan. Dominasi=1.0, Comeback=0.80, Reversal=0.70, Invasi=0.",
    "Last synced: {{date}}": "Terakhir disinkron: {{date}}",
    "Link copied! Share it with your kingdom players.": "Tautan tersalin! Bagikan dengan pemain kingdom Anda.",
    "Link to see match %": "Hubungkan untuk melihat % kecocokan",
    "Link your Discord account to receive roles based on your Atlas achievements:": "Hubungkan akun Discord Anda untuk menerima peran berdasarkan pencapaian Atlas:",
    "Link your Kingshot account first. Go to your Profile page and use the \"Link Kingshot Account\" section.": "Hubungkan akun Kingshot terlebih dahulu. Buka halaman Profil dan gunakan bagian \"Hubungkan Akun Kingshot\".",
    "Link your Kingshot account in your profile settings to use the Prep Scheduler.": "Hubungkan akun Kingshot di pengaturan profil untuk menggunakan Jadwal Prep.",
    "Link your Kingshot account on Atlas (TC 20+)": "Hubungkan akun Kingshot di Atlas (TC 20+)",
    "Link your Kingshot account, connect Discord, and join the Atlas server to become a settler.": "Hubungkan akun Kingshot, sambungkan Discord, dan gabung server Atlas untuk menjadi settler.",
    "Link your account to see personalized transfer matches": "Hubungkan akun Anda untuk melihat kecocokan transfer yang dipersonalisasi",
    "List your stats, playstyle, and what you're looking for. Recruiters find you — no cold-calling required.": "Cantumkan statistik, gaya bermain, dan apa yang Anda cari. Perekrut menemukan Anda — tanpa perlu cold-calling.",
    "Lock the schedule? This marks it as finalized.": "Kunci jadwal? Ini menandainya sebagai final.",
    "Loading K-{{num}}...": "Memuat K-{{num}}...",

    # === M long ===
    "Manual entry added for {{username}}.": "Entri manual ditambahkan untuk {{username}}.",
    "March times in seconds (0–120). Enter one — the other is estimated automatically.": "Waktu march dalam detik (0–120). Masukkan satu — yang lain diestimasi otomatis.",
    "Match Score (Best → Worst)": "Skor Kecocokan (Terbaik → Terburuk)",
    "Matchup data already added for KvK #{{num}}.": "Data pertandingan sudah ditambahkan untuk KvK #{{num}}.",
    "Matchups haven't been announced yet. Unlocks {{date}}.": "Pertandingan belum diumumkan. Terbuka {{date}}.",
    "Min {{count}} players": "Min {{count}} pemain",
    "Missing KvK #{{num}}": "KvK #{{num}} Hilang",
    "Missing KvKs (hover for date):": "KvK yang hilang (arahkan kursor untuk tanggal):",

    # === N-O long ===
    "No entries yet.": "Belum ada entri.",
    "No saved designs yet.": "Belum ada desain tersimpan.",

    # === P long ===
    "Permanently delete this archived schedule? All submissions, assignments, and change requests will be removed. This cannot be undone.": "Hapus permanen jadwal yang diarsipkan ini? Semua pengiriman, penugasan, dan permintaan perubahan akan dihapus. Ini tidak bisa dibatalkan.",
    "Pick any Bear Hunt day. Bot counts every 2 days from here.": "Pilih hari Bear Hunt mana saja. Bot menghitung setiap 2 hari dari sini.",
    "Pick your matchup. The numbers will tell the story.": "Pilih pertandingan Anda. Angka-angka akan bercerita.",
    "Pit any two kingdoms against each other. See who has the edge in Prep, Battle, and overall dominance.": "Adu dua kingdom mana pun. Lihat siapa yang unggul dalam Prep, Battle, dan dominasi keseluruhan.",
    "Place cities, traps, flags, resource points, and alliance buildings. Each type has its correct footprint — no guesswork.": "Tempatkan kota, jebakan, bendera, titik sumber daya, dan bangunan aliansi. Setiap jenis memiliki ukuran yang benar — tanpa tebak-tebakan.",
    "Plan offensive and defensive rallies simultaneously. Run two independent queues with different timing strategies.": "Rencanakan rally ofensif dan defensif secara bersamaan. Jalankan dua antrean independen dengan strategi timing berbeda.",
    "Play Schedule — UTC (1-3 ranges)": "Jadwal Main — UTC (1-3 rentang)",
    "Play your first KvK to unlock ranking history!": "Main KvK pertama untuk membuka riwayat peringkat!",
    "Play your first KvK to unlock score breakdown!": "Main KvK pertama untuk membuka rincian skor!",
    "Play your first KvK to unlock score history!": "Main KvK pertama untuk membuka riwayat skor!",
    "Play your first KvK to unlock score projections!": "Main KvK pertama untuk membuka proyeksi skor!",
    "Player ID must be 6-20 digits": "ID Pemain harus 6-20 digit",
    "Players submit their availability and speedups. The system auto-assigns 30-minute buff slots based on who brings the most value. No spreadsheets, no guesswork.": "Pemain mengirim ketersediaan dan speedup mereka. Sistem otomatis menetapkan slot buff 30 menit berdasarkan siapa yang memberikan nilai paling banyak. Tanpa spreadsheet, tanpa tebak-tebakan.",
    "Players upload a screenshot of their speedup inventory when submitting. Managers can verify claims before assigning slots. Trust, but verify.": "Pemain mengunggah tangkapan layar inventaris speedup saat mengirim. Manajer bisa memverifikasi klaim sebelum menetapkan slot. Percaya, tapi verifikasi.",
    "Players who are looking to transfer will appear here once they create a profile.": "Pemain yang ingin transfer akan muncul di sini setelah mereka membuat profil.",
    "Players will return here after submitting": "Pemain akan kembali ke sini setelah mengirim",
    "Please add availability for at least one day, or mark all days as skipped.": "Harap tambahkan ketersediaan untuk setidaknya satu hari, atau tandai semua hari sebagai dilewati.",
    "Please describe what is incorrect": "Harap jelaskan apa yang tidak benar",
    "Please enter at least 2 kingdom numbers": "Harap masukkan setidaknya 2 nomor kingdom",
    "Please enter your Player ID": "Harap masukkan ID Pemain Anda",
    "Please enter your username.": "Harap masukkan username Anda.",
    "Please select an error type": "Harap pilih jenis kesalahan",
    "Please select which KvK has the error": "Harap pilih KvK mana yang memiliki kesalahan",
    "Please upload a JPEG, PNG, GIF, or WebP image.": "Harap unggah gambar JPEG, PNG, GIF, atau WebP.",
    "Please upload a screenshot of your speedups.": "Harap unggah tangkapan layar speedup Anda.",
    "Please wait while we connect your accounts.": "Harap tunggu sementara kami menghubungkan akun Anda.",
    "Power (High → Low)": "Kekuatan (Tinggi → Rendah)",
    "Prefer a one-time contribution? Buy us a coffee on Ko-fi. Every bit helps keep the servers running.": "Lebih suka kontribusi sekali? Belikan kami kopi di Ko-fi. Setiap kontribusi membantu menjaga server tetap berjalan.",
    "Prep Phase hasn't ended yet. Unlocks {{date}}.": "Fase Prep belum berakhir. Terbuka {{date}}.",
    "Prep result already added for KvK #{{num}}.": "Hasil prep sudah ditambahkan untuk KvK #{{num}}.",
    "Prizes drawn live on Discord — smallest to biggest!": "Hadiah diundi langsung di Discord — dari terkecil hingga terbesar!",
    "Profile Comparison": "Perbandingan Profil",
    "Profile is taking a while to load.": "Profil membutuhkan waktu untuk memuat.",
    "Progress to {{tier}}": "Progres ke {{tier}}",
    "Progress: {{current}}/{{total}} ({{percent}}%)": "Progres: {{current}}/{{total}} ({{percent}}%)",
    "Provide additional evidence or context...": "Berikan bukti atau konteks tambahan...",
    "Provide any context or source for the correction...": "Berikan konteks atau sumber untuk koreksi...",
    "Pulls extreme rates toward 50% until you prove yourself": "Menarik rate ekstrem ke 50% sampai Anda membuktikan diri",
    "Put any kingdoms in the ring. Head-to-head stats, win rates, and Atlas Scores. Let the data crown the champion.": "Adu kingdom mana pun. Statistik head-to-head, win rate, dan Skor Atlas. Biarkan data menobatkan juara.",
}
