#!/usr/bin/env python3
"""Generate comprehensive Indonesian translation - Part 1: Translation dictionary A-G."""

T1 = {
    # === Short/common terms ===
    "d": "h",
    "h": "j",
    "m": "m",
    "s": "d",
    "Min": "Min",
    "Mon": "Sen",
    "Day": "Hari",
    "Days": "Hari",
    "Code": "Kode",
    "Ally": "Sekutu",
    "Enemy": "Musuh",
    "Loss": "Kalah",
    "Bye": "Bye",
    "Team": "Tim",
    "Event": "Event",
    "Events": "Event",
    "Field": "Bidang",
    "Image": "Gambar",
    "Local": "Lokal",
    "Other": "Lainnya",
    "Owner": "Pemilik",
    "Prep": "Prep",
    "Rally": "Rally",
    "Reply": "Balas",
    "Reset": "Reset",
    "Reason": "Alasan",
    "Recent": "Terbaru",
    "Import": "Impor",
    "Export": "Ekspor",
    "Detail": "Detail",
    "Rename": "Ganti Nama",
    "Remove": "Hapus",
    "Removed": "Dihapus",
    "Message": "Pesan",
    "Planner": "Planner",
    "Counter": "Counter",
    "Discord": "Discord",
    "Battle": "Battle",
    "Custom": "Kustom",
    "Browse": "Jelajahi",
    "Profile": "Profil",
    "Switch": "Ganti",
    "Preview": "Pratinjau",
    "Regular": "Reguler",
    "Admin": "Admin",
    "Admins": "Admin",
    "Alerts": "Peringatan",
    "Balance": "Saldo",
    "Bio": "Bio",
    "Block": "Blokir",
    "Blocked": "Diblokir",
    "Chance": "Peluang",
    "Change": "Ubah",
    "Comeback": "Comeback",
    "Columns": "Kolom",
    "Added": "Ditambahkan",
    "Reversal": "Reversal",
    "Advanced": "Lanjutan",
    "Analytics": "Analitik",
    "Performance": "Performa",
    "Progress": "Progres",
    "Support": "Dukungan",
    "Supporter": "Supporter",
    "Individual": "Individu",
    "Conversion": "Konversi",
    "Invalid": "Tidak Valid",
    "Invitational": "Undangan",
    "Atlas": "Atlas",
    "Create": "Buat",
    "Add": "Tambah",
    "Access": "Akses",
    "Success": "Berhasil",
    "Error": "Kesalahan",
    "Proof": "Bukti",
    "Info": "Info",
    "Overwrite": "Timpa",
    "Presets": "Preset",
    "Filters": "Filter",
    "Filter": "Filter",
    "Configured": "Dikonfigurasi",
    "Refresh": "Perbarui",
    "Load": "Muat",
    "Deploy": "Deploy",
    "Endorse": "Dukung",
    "Contribution": "Kontribusi",
    "Distribution": "Distribusi",
    "External": "Eksternal",
    "Candidates": "Kandidat",
    "Construction": "Konstruksi",
    "Consul": "Consul",
    "Consuls": "Consul",
    "Research": "Riset",
    "Resilience": "Ketangguhan",
    "Reminders": "Pengingat",
    "Delegates": "Delegasi",
    "Endorsements": "Dukungan",
    "Attempts": "Percobaan",
    "ACTIVE": "AKTIF",
    "DRAFT": "DRAF",
    "MANUAL": "MANUAL",
    "META": "META",
    "DATA": "DATA",
    "PLANNER": "PLANNER",
    "PLAYER": "PEMAIN",
    "RIVAL": "RIVAL",
    "KINGDOM": "KINGDOM",
    "TRANSFER": "TRANSFER",
    "RECRUITING": "MEREKRUT",
    "RECOMMENDED": "DIREKOMENDASIKAN",
    "ALLIES": "SEKUTU",
    "ENEMIES": "MUSUH",
    "DIRECTORY": "DIREKTORI",
    "COLONIES": "KOLONI",
    "REGISTRATION CLOSED": "REGISTRASI DITUTUP",

    # === A ===
    "ACCESS CONTROL": "KONTROL AKSES",
    "ADD BY ATLAS USERNAME": "TAMBAH DARI USERNAME ATLAS",
    "ADMIN PREVIEW": "PRATINJAU ADMIN",
    "ALLIANCE EVENTS": "EVENT ALIANSI",
    "ALLIANCE LEADERS": "PEMIMPIN ALIANSI",
    "AUTO-FILLED FROM LINKED ACCOUNT": "OTOMATIS DIISI DARI AKUN TERHUBUNG",
    "About codes:": "Tentang kode:",
    "Access Control": "Kontrol Akses",
    "Access Unlocked": "Akses Terbuka",
    "Account Found - Confirm Link": "Akun Ditemukan - Konfirmasi Hubungkan",
    "Activate pet buff timers when applicable.": "Aktifkan timer buff hewan peliharaan jika berlaku.",
    "Activated!": "Diaktifkan!",
    "Active Referrers": "Perujuk Aktif",
    "Active Reminders": "Pengingat Aktif",
    "Active Schedule": "Jadwal Aktif",
    "Actively Recruiting": "Aktif Merekrut",
    "Actively Recruiting Only": "Hanya yang Aktif Merekrut",
    "Ad-Free — Clean, distraction-free experience": "Bebas Iklan — Pengalaman bersih tanpa gangguan",
    "Add 2+ players to Rally Queue to generate call order": "Tambah 2+ pemain ke Antrean Rally untuk menghasilkan urutan panggilan",
    "Add Another Account": "Tambah Akun Lain",
    "Add Kingdom": "Tambah Kingdom",
    "Add KvK": "Tambah KvK",
    "Add Range": "Tambah Rentang",
    "Add Time Range": "Tambah Rentang Waktu",
    "Add a note to the recruiter": "Tambah catatan untuk perekrut",
    "Add event times (UTC).": "Tambah waktu event (UTC).",
    "Add players to Counter Queue to generate counter timing": "Tambah pemain ke Antrean Counter untuk menghasilkan timing counter",
    "Add to Your Server": "Tambah ke Server Anda",
    "Add your rally leaders — allies and enemies.": "Tambah pemimpin rally Anda — sekutu dan musuh.",
    "Add your rally leaders. No guesswork.": "Tambah pemimpin rally Anda. Tanpa tebak-tebakan.",
    "Admin access": "Akses admin",
    "After linking, return to the Transfer Hub to complete your endorsement.": "Setelah menghubungkan, kembali ke Transfer Hub untuk menyelesaikan dukungan Anda.",
    "After signing in, return to the Transfer Hub to complete your endorsement.": "Setelah masuk, kembali ke Transfer Hub untuk menyelesaikan dukungan Anda.",
    "All Alliances": "Semua Aliansi",
    "All Groups": "Semua Grup",
    "All Kingdoms": "Semua Kingdom",
    "All Languages": "Semua Bahasa",
    "All Players": "Semua Pemain",
    "All Regions": "Semua Wilayah",
    "All Registries": "Semua Registrasi",
    "All Severity": "Semua Tingkat",
    "All Submissions": "Semua Pengiriman",
    "All Tags": "Semua Tag",
    "All Tools": "Semua Alat",
    "Alliance Event Reminders": "Pengingat Event Aliansi",
    "Alliance Event Times": "Waktu Event Aliansi",
    "Alliance Information": "Informasi Aliansi",
    "Alliance Information & Schedules": "Informasi & Jadwal Aliansi",
    "Alliance Tag (3 chars)": "Tag Aliansi (3 karakter)",
    "Alliance tag is required": "Tag aliansi diperlukan",
    "Alliance tag must be exactly 3 characters.": "Tag aliansi harus tepat 3 karakter.",
    "Almost there!": "Hampir selesai!",
    "Already Activated!": "Sudah Diaktifkan!",
    "Already S-Tier! You're in the elite.": "Sudah S-Tier! Anda di golongan elite.",
    "Already an admin.": "Sudah menjadi admin.",
    "Alt Account": "Akun Alt",
    "Alt account username": "Username akun alt",
    "Ambassador": "Ambassador",
    "Any Alliance": "Semua Aliansi",
    "Any Time": "Kapan Saja",
    "Any additional context...": "Konteks tambahan apa pun...",
    "Any instructions or reminders...": "Instruksi atau pengingat apa pun...",
    "Any notes for the manager...": "Catatan untuk manajer...",
    "Appeal Rejection": "Penolakan Banding",
    "Appeal submitted:": "Banding diajukan:",
    "Application Slots": "Slot Lamaran",
    "Apply as Co-Editor": "Lamar sebagai Co-Editor",
    "Apply to": "Lamar ke",
    "Apply to Transfer": "Lamar untuk Transfer",
    "Applying...": "Mendaftar...",
    "Are you sure you want to cancel? You can always resubscribe later.": "Yakin ingin membatalkan? Anda selalu bisa berlangganan kembali nanti.",
    "Are you sure?": "Apakah Anda yakin?",
    "As a Supporter, you can manage bot settings for multiple Discord servers.": "Sebagai Supporter, Anda dapat mengelola pengaturan bot untuk beberapa server Discord.",
    "Assign player names to city blocks and time slots to traps. Everyone knows exactly where they belong.": "Tetapkan nama pemain ke blok kota dan slot waktu ke jebakan. Semua tahu persis di mana mereka seharusnya.",
    "Assigned by": "Ditetapkan oleh",
    "Assigning...": "Menetapkan...",
    "At least one day must remain enabled.": "Setidaknya satu hari harus tetap aktif.",
    "Atlas Bot": "Atlas Bot",
    "Atlas Bot Dashboard": "Dasbor Atlas Bot",
    "Atlas Discord Bot": "Atlas Discord Bot",
    "Atlas Legend": "Atlas Legend",
    "Atlas Recruiter": "Perekrut Atlas",
    "Atlas Score & Rankings": "Skor & Peringkat Atlas",
    "Atlas Score (High → Low)": "Skor Atlas (Tinggi → Rendah)",
    "Atlas Score Breakdown": "Rincian Skor Atlas",
    "Atlas Score History": "Riwayat Skor Atlas",
    "Atlas Score Simulator": "Simulator Skor Atlas",
    "Atlas Supporter": "Atlas Supporter",
    "Atlas Supporter Perk": "Keuntungan Atlas Supporter",
    "Atlas Supporter role for subscribers": "Peran Atlas Supporter untuk pelanggan",
    "Atlas account created": "Akun Atlas dibuat",
    "Attribution Sources": "Sumber Atribusi",
    "Authorized Users": "Pengguna Resmi",
    "Auto-Assign": "Auto-Assign",
    "Auto-Assign & Export": "Auto-Assign & Ekspor",

    # === B ===
    "Back to Schedules": "Kembali ke Jadwal",
    "Base Win Rate": "Win Rate Dasar",
    "Base image copied to clipboard!": "Gambar base tersalin ke clipboard!",
    "Base image downloaded!": "Gambar base terunduh!",
    "Battle L": "Kalah Battle",
    "Battle Manager removed.": "Battle Manager dihapus.",
    "Battle Managers": "Battle Manager",
    "Battle Phase (Castle Soon)": "Fase Battle (Castle Segera)",
    "Battle Planner": "Battle Planner",
    "Battle Registry": "Battle Registry",
    "Battle W": "Menang Battle",
    "Battle Win": "Menang Battle",
    "Become a Co-Editor": "Jadi Co-Editor",
    "Become a Kingdom Editor": "Jadi Editor Kingdom",
    "Become a Supporter →": "Jadi Supporter →",
    "Become an Atlas Supporter": "Jadi Atlas Supporter",
    "Before you go, help us improve Atlas for everyone.": "Sebelum pergi, bantu kami tingkatkan Atlas untuk semua.",
    "Block specific users from your dashboard. Only the right people manage your server's bot config.": "Blokir pengguna tertentu dari dasbor Anda. Hanya orang yang tepat yang mengelola konfigurasi bot server Anda.",
    "Bot Atlas": "Bot Atlas",
    "Bot Dashboard — Atlas": "Dasbor Bot — Atlas",
    "Bot pings before events.": "Bot ping sebelum event.",
    "Bottom 50% — Rebuilding": "Bawah 50% — Membangun kembali",
    "Bronze badge on listing": "Lencana Perunggu di daftar",
    "Browse Kingdoms": "Jelajahi Kingdom",
    "Browse Transfer Hub →": "Jelajahi Transfer Hub →",
    "Browse open kingdoms and find your next home": "Jelajahi kingdom terbuka dan temukan rumah baru Anda",
    "Browse recruit candidates": "Jelajahi kandidat rekrut",
    "Buffed ⚡": "Di-buff ⚡",
    "By Alliance": "Berdasarkan Aliansi",
    "By Kingdom": "Berdasarkan Kingdom",
    "By Region": "Berdasarkan Wilayah",

    # === C ===
    "CALL NOW": "PANGGIL SEKARANG",
    "CONNECTED SERVERS": "SERVER TERHUBUNG",
    "CURRENT DATA": "DATA SAAT INI",
    "Calculate smarter. Grow faster.": "Hitung lebih cerdas. Tumbuh lebih cepat.",
    "Campaign Winners": "Pemenang Kampanye",
    "Can't Attend": "Tidak Bisa Hadir",
    "Cannot remove owner": "Tidak bisa hapus pemilik",
    "Cannot remove yourself": "Tidak bisa hapus diri sendiri",
    "Castle Battle": "Castle Battle",
    "Castle Rotation": "Rotasi Castle",
    "Chain Hits": "Serangan Berantai",
    "Chain Hits — stagger rallies at custom intervals": "Serangan Berantai — atur rally dengan interval kustom",
    "Change Screenshot": "Ubah Tangkapan Layar",
    "Change Slot": "Ubah Slot",
    "Change request resolved.": "Permintaan perubahan diselesaikan.",
    "Change request submitted! Your Prep Manager will be notified.": "Permintaan perubahan dikirim! Manajer Prep Anda akan diberitahu.",
    "Channel ID": "ID Channel",
    "Characteristics": "Karakteristik",
    "Chat with players in your kingdom range": "Ngobrol dengan pemain di rentang kingdom Anda",
    "Check it out →": "Lihat →",
    "Checking editor status...": "Memeriksa status editor...",
    "Checking your Discord servers...": "Memeriksa server Discord Anda...",
    "Checking your in-game name...": "Memeriksa nama in-game Anda...",
    "Checking...": "Memeriksa...",
    "Choose Channel": "Pilih Channel",
    "Claim No Longer Active": "Klaim Tidak Lagi Aktif",
    "Claim Your Kingdom": "Klaim Kingdom Anda",
    "Claim your kingdom": "Klaim kingdom Anda",
    "Clear All Filters": "Hapus Semua Filter",
    "Clear Day": "Hapus Hari",
    "Clear Filters": "Hapus Filter",
    "Clear Selection": "Hapus Pilihan",
    "Clear all": "Hapus semua",
    "Closed Registry": "Registrasi Ditutup",
    "Closed Schedule": "Jadwal Ditutup",
    "Co-Editor": "Co-Editor",
    "Co-Editor Invitation": "Undangan Co-Editor",
    "Co-Editor Request Pending": "Permintaan Co-Editor Tertunda",
    "Co-Editor Request Sent": "Permintaan Co-Editor Terkirim",
    "Co-Editor Requests": "Permintaan Co-Editor",
    "Co-editor request approved!": "Permintaan co-editor disetujui!",
    "Co-editor request declined.": "Permintaan co-editor ditolak.",
    "Community Reviews": "Ulasan Komunitas",
    "Community reviews from players": "Ulasan komunitas dari pemain",
    "Compare up to 2 kingdoms side-by-side": "Bandingkan hingga 2 kingdom berdampingan",
    "Comparison": "Perbandingan",
    "Complete Profile": "Lengkapi Profil",
    "Complete your profile for better Match Scores and more recruiter visibility.": "Lengkapi profil Anda untuk Skor Kecocokan lebih baik dan visibilitas perekrut lebih tinggi.",
    "Config duplicated": "Konfigurasi diduplikasi",
    "Confirm Application": "Konfirmasi Lamaran",
    "Contact Method": "Metode Kontak",
    "Contact name *": "Nama kontak *",
    "Continue Browsing": "Lanjut Menjelajah",
    "Continue to Transfer Hub": "Lanjut ke Transfer Hub",
    "Contribute to Kingdom Fund": "Kontribusi ke Kingdom Fund",
    "Contribution History": "Riwayat Kontribusi",
    "Contribution Successful!": "Kontribusi Berhasil!",
    "Contribution link copied! Share with your kingdom.": "Tautan kontribusi tersalin! Bagikan dengan kingdom Anda.",
    "Contributions boost listing visibility and unlock tier benefits": "Kontribusi meningkatkan visibilitas daftar dan membuka keuntungan tier",
    "Conversion Rate": "Tingkat Konversi",
    "Copied": "Tersalin",
    "Copy Code": "Salin Kode",
    "Copy Contribution Link": "Salin Tautan Kontribusi",
    "Copy Listing Link": "Salin Tautan Daftar",
    "Copy Player List": "Salin Daftar Pemain",
    "Copy for Discord": "Salin untuk Discord",
    "Copy from": "Salin dari",
    "Copy preview": "Salin pratinjau",
    "Could not generate share link": "Tidak bisa membuat tautan bagikan",
    "Could not reach server.": "Tidak bisa mencapai server.",
    "Counter timeline appears when you have players queued": "Timeline counter muncul saat Anda memiliki pemain dalam antrean",
    "Crashes (24h)": "Crash (24j)",
    "Create Profile": "Buat Profil",
    "Creating...": "Membuat...",
    "Critical": "Kritis",
    "Current Co-Editors": "Co-Editor Saat Ini",
    "Current Score": "Skor Saat Ini",
    "Currently viewing": "Sedang melihat",

    # === D ===
    "DEFAULT REMINDER CHANNEL": "CHANNEL PENGINGAT DEFAULT",
    "Data Unavailable": "Data Tidak Tersedia",
    "Deadline": "Tenggat Waktu",
    "Deadline (optional)": "Tenggat Waktu (opsional)",
    "Deadline is in UTC": "Tenggat waktu dalam UTC",
    "Deadline passed": "Tenggat waktu lewat",
    "Deadline updated.": "Tenggat waktu diperbarui.",
    "Delegate added successfully": "Delegasi berhasil ditambahkan",
    "Delegate must be in the same kingdom as you": "Delegasi harus di kingdom yang sama dengan Anda",
    "Delegate removed": "Delegasi dihapus",
    "Delete Schedule": "Hapus Jadwal",
    "Deploy failed": "Deploy gagal",
    "Deploy to Discord": "Deploy ke Discord",
    "Deployed to Discord!": "Berhasil deploy ke Discord!",
    "Design Name": "Nama Desain",
    "Design name...": "Nama desain...",
    "Detailed Kingdom Profiles": "Profil Kingdom Detail",
    "Details (optional)": "Detail (opsional)",
    "Detect More Servers": "Deteksi Server Lainnya",
    "Detect My Servers": "Deteksi Server Saya",
    "Disable Stagger": "Nonaktifkan Stagger",
    "Disconnects": "Pemutusan",
    "Discord Bot Atlas": "Discord Bot Atlas",
    "Discord Role — Exclusive Supporter role & badge": "Peran Discord — Peran & lencana Supporter eksklusif",
    "Discord Supporter Role": "Peran Supporter Discord",
    "Discord account unlinked": "Akun Discord terputus",
    "Discord authorization was cancelled": "Otorisasi Discord dibatalkan",
    "Discord integration is not configured yet": "Integrasi Discord belum dikonfigurasi",
    "Discord linked on Atlas": "Discord terhubung di Atlas",
    "Discord message copied!": "Pesan Discord tersalin!",
    "Discord username": "Username Discord",
    "Dismiss notification": "Tutup notifikasi",
    "Do the same for the Counter Queue if needed.": "Lakukan hal yang sama untuk Antrean Counter jika diperlukan.",
    "Download CSV": "Unduh CSV",
    "Download PNG": "Unduh PNG",
    "Downloaded!": "Terunduh!",
    "Draft restored": "Draf dipulihkan",
    "Drag players to Rally or Counter queue": "Seret pemain ke antrean Rally atau Counter",
    "Drag to reorder": "Seret untuk menyusun ulang",
    "Drop players here or click to add": "Letakkan pemain di sini atau klik untuk menambah",
    "Duplicate config": "Duplikasi konfigurasi",
    "d left": "h tersisa",

    # === E ===
    "EMBED MESSAGE": "PESAN EMBED",
    "EMBED TITLE": "JUDUL EMBED",
    "EMOJI → ROLE MAPPINGS": "EMOJI → PEMETAAN PERAN",
    "Early Access — First to try new features": "Akses Awal — Pertama mencoba fitur baru",
    "Edit Deadline": "Edit Tenggat Waktu",
    "Edit Message": "Edit Pesan",
    "Edit Opt-Outs": "Edit Opt-Out",
    "Edit Player": "Edit Pemain",
    "Edit Player Entry": "Edit Entri Pemain",
    "Edit Speedups": "Edit Speedup",
    "Edit entry": "Edit entri",
    "Edit failed": "Edit gagal",
    "Edit your speedups, availability, or other details.": "Edit speedup, ketersediaan, atau detail lainnya.",
    "Editing your existing response": "Mengedit respons Anda yang ada",
    "Editor": "Editor",
    "Elite": "Elite",
    "Email (optional, for follow-up)": "Email (opsional, untuk tindak lanjut)",
    "Embed Code": "Kode Embed",
    "Embed code copied!": "Kode embed tersalin!",
    "Enable Stagger": "Aktifkan Stagger",
    "Enabled Days": "Hari yang Diaktifkan",
    "Endorsement Not Found": "Dukungan Tidak Ditemukan",
    "Endorsing...": "Mendukung...",
    "Enter correct value": "Masukkan nilai yang benar",
    "Enter player name and march times": "Masukkan nama pemain dan waktu march",
    "Enter your numeric Player ID": "Masukkan ID Pemain numerik Anda",
    "Entry deleted.": "Entri dihapus.",
    "Error Loading Transfer Hub": "Gagal Memuat Transfer Hub",
    "Error removing assignment.": "Gagal menghapus penugasan.",
    "Event Times": "Waktu Event",
    "Everything in Bronze": "Semua yang ada di Perunggu",
    "Everything in Silver": "Semua yang ada di Perak",
    "Everything you need, one slash away.": "Semua yang Anda butuhkan, satu perintah.",

    # === F ===
    "FORM CLOSED": "FORMULIR DITUTUP",
    "Featured Review": "Ulasan Unggulan",
    "Fill Form Yourself": "Isi Formulir Sendiri",
    "Fill out the form below": "Isi formulir di bawah",
    "Find allies, scout rivals, connect with the community": "Temukan sekutu, intai rival, hubungkan dengan komunitas",
    "Find the perfect kingdom for you — or the best recruits.": "Temukan kingdom sempurna untuk Anda — atau rekrut terbaik.",
    "Find the perfect kingdom for you. No more blind transfers.": "Temukan kingdom sempurna untuk Anda. Tidak ada lagi transfer buta.",

    # === G ===
    "Gold Tier": "Gold Tier",
    "Gold Tier Kingdom Feature": "Fitur Kingdom Gold Tier",

    # Parameterized strings
    "(Free)": "(Gratis)",
    "(breakdown is approximate)": "(rincian bersifat perkiraan)",
    "+ Add": "+ Tambah",
    "+ Add KvK": "+ Tambah KvK",
    "+ Add Mapping": "+ Tambah Pemetaan",
    "+ Add Review": "+ Tambah Ulasan",
    "+ Add Time Range": "+ Tambah Rentang Waktu",
    "+ Add a Server": "+ Tambah Server",
    "+ Ally": "+ Sekutu",
    "+ Enemy": "+ Musuh",
    "+ New Role Assigner": "+ Penugasan Peran Baru",
    "+ Save Current": "+ Simpan Saat Ini",
    "+ Server": "+ Server",
    "-- Select a field --": "-- Pilih bidang --",
    "1,300+ kingdoms": "1.300+ kingdom",
    "d left": "h tersisa",
}
