#!/usr/bin/env python3
"""Generate comprehensive Indonesian translation - Part 4: Long strings and parameterized."""

T4 = {
    # === Long descriptive strings ===
    "A full 1200×1200 isometric grid that mirrors the in-game alliance territory. Zoom, pan, and navigate just like the real map.": "Grid isometrik 1200×1200 penuh yang mencerminkan wilayah aliansi in-game. Zoom, geser, dan navigasi seperti peta asli.",
    "A design named \"{{name}}\" already exists. Saving will overwrite it.": "Desain bernama \"{{name}}\" sudah ada. Menyimpan akan menimpa.",
    "A similar correction for {{field}} is already pending review": "Koreksi serupa untuk {{field}} sudah menunggu peninjauan",
    "A similar error report is already pending review": "Laporan kesalahan serupa sudah menunggu peninjauan",
    "Admins can edit reminders and settings. Only add users with Manage Server Discord permission.": "Admin bisa mengedit pengingat dan pengaturan. Hanya tambah pengguna dengan izin Manage Server Discord.",
    "All alerts and reminders go here unless overridden individually.": "Semua peringatan dan pengingat masuk di sini kecuali diganti secara individual.",
    "All available servers are already registered.": "Semua server yang tersedia sudah terdaftar.",
    "All contributions and weekly maintenance charges for your kingdom fund.": "Semua kontribusi dan biaya pemeliharaan mingguan untuk dana kingdom Anda.",
    "Allies → Rally Queue. Enemies → Counter Queue. Long-press to edit.": "Sekutu → Antrean Rally. Musuh → Antrean Counter. Tekan lama untuk edit.",
    "Allies → Rally Queue. Enemies → Counter Queue. Right-click to edit.": "Sekutu → Antrean Rally. Musuh → Antrean Counter. Klik kanan untuk edit.",
    "Ambassador Discord role + badge. Priority support, #vip-lounge access, leaderboard spotlight, and direct input on Atlas features.": "Peran & lencana Ambassador Discord. Dukungan prioritas, akses #vip-lounge, sorotan papan peringkat, dan masukan langsung untuk fitur Atlas.",
    "Ambassador roles for top referrers": "Peran Ambassador untuk perujuk teratas",
    "An Editor, Co-Editor, or Prep Manager creates a Prep Schedule for their Silver+ Tier kingdom and sets an optional submission deadline.": "Editor, Co-Editor, atau Manajer Prep membuat Jadwal Prep untuk kingdom Silver+ Tier mereka dan menetapkan tenggat pengiriman opsional.",
    "An active registry already exists for this kingdom. Close or archive it first.": "Registrasi aktif sudah ada untuk kingdom ini. Tutup atau arsipkan terlebih dahulu.",
    "An active schedule already exists for this kingdom{{kvk}}. Close or archive it first.": "Jadwal aktif sudah ada untuk kingdom ini{{kvk}}. Tutup atau arsipkan terlebih dahulu.",
    "Another editor has endorsed this kingdom.": "Editor lain telah mendukung kingdom ini.",
    "Anyone with <strong>Manage Server</strong> permission in your Discord server can access this dashboard — no setup needed. The server owner can block specific users below.": "Siapa pun dengan izin <strong>Manage Server</strong> di server Discord Anda bisa mengakses dasbor ini — tanpa pengaturan. Pemilik server bisa memblokir pengguna tertentu di bawah.",
    "Applicants land in your inbox. View their profiles, mark as Interested, Accept, or Decline. The right players come to you.": "Pelamar masuk ke kotak masuk Anda. Lihat profil mereka, tandai Tertarik, Terima, atau Tolak. Pemain yang tepat datang kepada Anda.",
    "Archive this schedule? It will no longer accept submissions.": "Arsipkan jadwal ini? Tidak akan menerima pengiriman lagi.",
    "As a Supporter, you can manage bot settings for multiple Discord servers.": "Sebagai Supporter, Anda bisa mengelola pengaturan bot untuk beberapa server Discord.",
    "Ask your alliance to chip in — recruiting benefits everyone in the kingdom.": "Minta aliansi Anda ikut kontribusi — rekrutmen menguntungkan semua orang di kingdom.",
    "Assigned by Editors to run the day-to-day. Review submissions, auto-assign slots, export schedules, handle change requests.": "Ditugaskan oleh Editor untuk menjalankan operasi harian. Tinjau pengiriman, tetapkan slot otomatis, ekspor jadwal, tangani permintaan perubahan.",
    "Atlas Bot must be in your Discord server.": "Atlas Bot harus ada di server Discord Anda.",
    "Atlas Bot needs the \"Add Reactions\" permission in the target channel.": "Atlas Bot memerlukan izin \"Add Reactions\" di channel target.",
    "Atlas Bot needs the \"Manage Roles\" permission.": "Atlas Bot memerlukan izin \"Manage Roles\".",
    "Atlas Bot's role must be <em>above</em> the roles it assigns in Server Settings → Roles. Otherwise Discord will block the assignment.": "Peran Atlas Bot harus <em>di atas</em> peran yang ditetapkan di Server Settings → Roles. Jika tidak, Discord akan memblokir penetapan.",
    "Atlas Bot's role must be above the roles it assigns.": "Peran Atlas Bot harus di atas peran yang ditetapkan.",
    "Atlas Supporters fund the servers, database, and development that keep 1200+ kingdom profiles accurate and free for everyone.": "Atlas Supporter membiayai server, database, dan pengembangan yang menjaga 1200+ profil kingdom akurat dan gratis untuk semua.",
    "Atlas Supporters get unlimited access — every rally, every KvK.": "Atlas Supporter mendapat akses tak terbatas — setiap rally, setiap KvK.",
    "Atlas is a community project built by players, for players. Your support keeps the lights on and new features coming.": "Atlas adalah proyek komunitas yang dibangun oleh pemain, untuk pemain. Dukungan Anda menjaga semuanya berjalan dan fitur baru terus hadir.",
    "Atlas is community-built and transparent — our code is open for review": "Atlas dibangun komunitas dan transparan — kode kami terbuka untuk ditinjau",
    "Badge, Battle Planner, unlimited bot commands, bulk gift code redeem — and the satisfaction of funding the tools you actually use.": "Lencana, Battle Planner, perintah bot tak terbatas, redeem kode hadiah massal — dan kepuasan membiayai alat yang Anda gunakan.",
    "Based on your Transfer Profile preferences vs this kingdom's listing.": "Berdasarkan preferensi Profil Transfer Anda vs daftar kingdom ini.",
    "Based on your kingdom requirements": "Berdasarkan persyaratan kingdom Anda",
    "Based on your listing criteria": "Berdasarkan kriteria daftar Anda",
    "Basic listing with Atlas Score & stats": "Daftar dasar dengan Skor Atlas & statistik",
    "Battle result already added for KvK #{{num}}.": "Hasil battle sudah ditambahkan untuk KvK #{{num}}.",
    "Battle-tested rating that rewards experience and consistency. One number tells you who's a real threat vs a lucky newcomer.": "Rating teruji yang menghargai pengalaman dan konsistensi. Satu angka memberitahu siapa ancaman nyata vs pendatang baru yang beruntung.",
    "Bayesian adjustment:": "Penyesuaian Bayesian:",
    "Bayesian rating. Experience matters. No more lucky newcomers.": "Rating Bayesian. Pengalaman itu penting. Tidak ada lagi pendatang baru yang beruntung.",
    "Be online during your assigned slot": "Online saat slot Anda yang ditetapkan",
    "Be the first. Share Atlas, rack up referrals, and own this leaderboard.": "Jadilah yang pertama. Bagikan Atlas, kumpulkan referral, dan kuasai papan peringkat ini.",
    "Bear Hunt, Viking Vengeance, Swordland Showdown, Tri-Alliance Clash — timed reminders so nobody misses the fight.": "Bear Hunt, Viking Vengeance, Swordland Showdown, Tri-Alliance Clash — pengingat tepat waktu agar tidak ada yang melewatkan pertarungan.",
    "Become the editor for your kingdom's Transfer Hub listing. As editor, you control recruitment settings, review applications, and manage your kingdom's public profile.": "Jadi editor untuk daftar Transfer Hub kingdom Anda. Sebagai editor, Anda mengontrol pengaturan rekrutmen, meninjau lamaran, dan mengelola profil publik kingdom Anda.",
    "Billed ${{amount}}/year": "Ditagih ${{amount}}/tahun",
    "Blocked users cannot access this server's dashboard even if they have Manage Server permission.": "Pengguna yang diblokir tidak bisa mengakses dasbor server ini meskipun memiliki izin Manage Server.",
    "Bring kingdom intelligence directly to your Discord server. Look up kingdoms, compare matchups, and check rankings — without leaving Discord.": "Bawa intelijen kingdom langsung ke server Discord Anda. Cari kingdom, bandingkan pertandingan, dan periksa peringkat — tanpa meninggalkan Discord.",
    "Browse every kingdom with Atlas Scores, KvK records, and community reviews. Create a Transfer Profile, apply directly, and track your applications. Match Scores show which kingdoms fit your playstyle.": "Jelajahi setiap kingdom dengan Skor Atlas, catatan KvK, dan ulasan komunitas. Buat Profil Transfer, lamar langsung, dan lacak lamaran Anda. Skor Kecocokan menunjukkan kingdom mana yang sesuai gaya bermain Anda.",
    "Browse kingdoms below and hit Apply when you find the right fit.": "Jelajahi kingdom di bawah dan klik Lamar saat menemukan yang tepat.",
    "Buy us a coffee, fund a feature, or just say thanks ☕": "Belikan kami kopi, danai fitur, atau ucapkan terima kasih ☕",
    "Calculate exact call delays so every rally lands on the same building within seconds of each other. No more counting on your fingers.": "Hitung delay panggilan tepat agar setiap rally mendarat di bangunan yang sama dalam hitungan detik. Tidak perlu hitung pakai jari lagi.",
    "Chip In to Fund": "Kontribusi ke Dana",
    "Claim Kingdom {{kingdom}} to manage its recruitment listing.": "Klaim Kingdom {{kingdom}} untuk mengelola daftar rekrutmennya.",
    "Claim Kingdom {{num}}": "Klaim Kingdom {{num}}",
    "Claim your kingdom, set requirements, add vibe tags, and describe what makes your kingdom worth joining. Your listing is always live.": "Klaim kingdom Anda, tetapkan persyaratan, tambah tag suasana, dan jelaskan apa yang membuat kingdom Anda layak diikuti. Daftar Anda selalu aktif.",
    "Claim your kingdom, set up your listing with requirements and vibe tags, and review incoming applications. Fund your listing to unlock better visibility and features like invites and priority placement.": "Klaim kingdom Anda, atur daftar dengan persyaratan dan tag suasana, dan tinjau lamaran masuk. Danai daftar Anda untuk membuka visibilitas dan fitur yang lebih baik seperti undangan dan penempatan prioritas.",
    "Click \"+ Add KvK\" to add results starting from KvK #{{kvk}}": "Klik \"+ Tambah KvK\" untuk menambah hasil mulai dari KvK #{{kvk}}",
    "Click + Add Ally or + Add Enemy above": "Klik + Tambah Sekutu atau + Tambah Musuh di atas",
    "Click <strong>{{deploy}}</strong> — Atlas Bot will post the message and add reactions.": "Klik <strong>{{deploy}}</strong> — Atlas Bot akan memposting pesan dan menambah reaksi.",
    "Click a player to view details. Editors can edit speedups and opt-outs.": "Klik pemain untuk melihat detail. Editor bisa mengedit speedup dan opt-out.",
    "Click or drag players into the Rally Queue.": "Klik atau seret pemain ke Antrean Rally.",
    "Close the form? No new submissions or edits will be allowed.": "Tutup formulir? Tidak ada pengiriman atau edit baru yang diperbolehkan.",
    "Code \"{{code}}\" not found in your in-game name. Change your name to include it, wait a moment, then try again.": "Kode \"{{code}}\" tidak ditemukan di nama in-game Anda. Ubah nama Anda untuk menyertakannya, tunggu sebentar, lalu coba lagi.",
    "Codes sourced from {{source}}.": "Kode bersumber dari {{source}}.",
    "Collect player availability and troop levels for KvK Castle Battles. Know who's showing up, what they're bringing, and plan your castle hit with real data.": "Kumpulkan ketersediaan pemain dan level pasukan untuk KvK Castle Battle. Ketahui siapa yang hadir, apa yang mereka bawa, dan rencanakan serangan castle dengan data nyata.",
    "Combined Prep (45%) + Battle (55%) win rates with Bayesian adjustment. No inflated scores from lucky starts.": "Win rate Prep (45%) + Battle (55%) gabungan dengan penyesuaian Bayesian. Tidak ada skor berlebihan dari awal yang beruntung.",
    "Comprehensive rating based on win rates, performance patterns, recent form, and experience. Rewards consistency over lucky streaks.": "Rating komprehensif berdasarkan win rate, pola performa, kondisi terkini, dan pengalaman. Menghargai konsistensi dibanding keberuntungan.",
    "Connect your in-game account to auto-fill your profile with your avatar, username, kingdom, and Town Center level.": "Hubungkan akun in-game Anda untuk auto-fill profil dengan avatar, username, kingdom, dan level Town Center.",
    "Connect your kingdom to unlock submissions and track your contributions.": "Hubungkan kingdom Anda untuk membuka pengiriman dan melacak kontribusi.",
    "Connected via Discord sign-in. Eligible roles will be synced automatically.": "Terhubung melalui masuk Discord. Peran yang memenuhi syarat akan disinkronkan otomatis.",
    "Continue with {{provider}}": "Lanjutkan dengan {{provider}}",
    "Contribute ${{amount}}": "Kontribusi ${{amount}}",
    "Contribute to your kingdom fund to unlock tier features and customize your listing.": "Kontribusi ke dana kingdom untuk membuka fitur tier dan menyesuaikan daftar Anda.",
    "Contributing to your Kingdom Fund unlocks Bronze → Silver → Gold tiers with better visibility and features. Funds deplete ~$5/week.": "Berkontribusi ke Kingdom Fund membuka tier Perunggu → Perak → Emas dengan visibilitas dan fitur lebih baik. Dana berkurang ~$5/minggu.",
    "Coordinate Castle Appointments for KvK Prep Phase. Collect player speedups & availability, then auto-assign optimal buff slots. Make every 30 minutes count.": "Koordinasikan Janji Castle untuk Fase Prep KvK. Kumpulkan speedup & ketersediaan pemain, lalu tetapkan slot buff optimal secara otomatis. Manfaatkan setiap 30 menit.",
    "Coordinate directly with players in your kingdom range. Each group has its own channel.": "Koordinasi langsung dengan pemain di rentang kingdom Anda. Setiap grup memiliki channel sendiri.",
    "Coordinate multi-rally strikes with surgical precision. Set march times, call orders, and hit windows — so your alliance lands together, every time. Currently in development.": "Koordinasikan serangan multi-rally dengan presisi bedah. Atur waktu march, urutan panggilan, dan jendela serangan — agar aliansi Anda mendarat bersamaan, setiap saat. Sedang dalam pengembangan.",
    "Coordinate your kingdom's KvK prep phase": "Koordinasikan fase prep KvK kingdom Anda",
    "Create a Battle Registry for your Silver+ Tier kingdom and share the link with players so they can register their availability.": "Buat Battle Registry untuk kingdom Silver+ Tier dan bagikan tautan ke pemain agar mereka bisa mendaftar ketersediaan.",
    "Create your Transfer Profile and apply to kingdoms": "Buat Profil Transfer Anda dan lamar ke kingdom",
    "Create your first Battle Registry above to collect player availability for castle battles.": "Buat Battle Registry pertama Anda di atas untuk mengumpulkan ketersediaan pemain untuk castle battle.",
    "Create your first Prep Schedule above to coordinate Castle Appointments for your kingdom.": "Buat Jadwal Prep pertama Anda di atas untuk mengkoordinasikan Janji Castle untuk kingdom Anda.",
    "Current win streaks provide a boost. Battle: +1.1% per win (max 10). Prep: +1% per win (max 10).": "Streak kemenangan saat ini memberikan bonus. Battle: +1.1% per kemenangan (maks 10). Prep: +1% per kemenangan (maks 10).",
    "Customize the title, message, and add emoji → role mappings.": "Sesuaikan judul, pesan, dan tambahkan pemetaan emoji → peran.",
    "Data Hunter": "Data Hunter",
    "Data Master": "Data Master",
    "Data Scout": "Data Scout",
    "Define territory with Banners/HQ. Other buildings must be placed within territory zones.": "Tentukan wilayah dengan Banner/HQ. Bangunan lain harus ditempatkan di zona wilayah.",
    "Define your alliance territory by placing Banners or HQ. Cities, Traps, and Special buildings can only be placed within territory zones (shown in green).": "Tentukan wilayah aliansi Anda dengan menempatkan Banner atau HQ. Kota, Jebakan, dan Bangunan Spesial hanya bisa ditempatkan di zona wilayah (ditunjukkan hijau).",
    "Delegated access from {{name}}": "Akses didelegasikan dari {{name}}",
    "Delete \"{{name}}\"?": "Hapus \"{{name}}\"?",
    "Depositing is 100% optional. The Transfer Hub is free for everyone. Fund tiers just give your kingdom extra visibility.": "Deposit 100% opsional. Transfer Hub gratis untuk semua. Tier dana hanya memberikan visibilitas ekstra ke kingdom Anda.",
    "Direct visual comparison with overlapping metrics. Hover over datasets to highlight.": "Perbandingan visual langsung dengan metrik tumpang tindih. Arahkan kursor ke dataset untuk menyorot.",
    "Discord Role — Exclusive Supporter role & badge": "Peran Discord — Peran & lencana Supporter eksklusif",
    "Discord requires browser login for security. Check \"Remember me\" for faster future logins. You'll be redirected back automatically.": "Discord memerlukan login browser untuk keamanan. Centang \"Ingat saya\" untuk login lebih cepat di masa depan. Anda akan dialihkan kembali secara otomatis.",
    "Dominations boost your score up to +15%. Invasions hurt equally. Rewards consistent double-phase performance.": "Dominasi meningkatkan skor Anda hingga +15%. Invasi merugikan secara setara. Menghargai performa double-phase yang konsisten.",
    "Dominations, form, and streaks compound your base score": "Dominasi, kondisi, dan streak menggabungkan skor dasar Anda",
    "Each qualifying Settler = 1 raffle ticket for their kingdom": "Setiap Settler yang memenuhi syarat = 1 tiket undian untuk kingdom mereka",
    "Each rally hits X seconds after the previous one": "Setiap rally menghantam X detik setelah yang sebelumnya",
    "Editors & Co-Editors can designate Battle Managers": "Editor & Co-Editor bisa menunjuk Battle Manager",
    "Editors or Battle Managers create a registry for the upcoming KvK Castle Battle.": "Editor atau Battle Manager membuat registrasi untuk KvK Castle Battle yang akan datang.",
    "Editors, Co-Editors, and Prep Managers of Silver+ Tier kingdoms can create and manage schedules.": "Editor, Co-Editor, dan Manajer Prep dari kingdom Silver+ Tier bisa membuat dan mengelola jadwal.",
    "Enter each rally caller with their march times to the target building.": "Masukkan setiap pemanggil rally dengan waktu march mereka ke bangunan target.",
    "Enter the Player ID of your other in-game account. A quick ownership check will follow.": "Masukkan ID Pemain akun in-game lain Anda. Pemeriksaan kepemilikan cepat akan menyusul.",
    "Enter the coordinate range of your alliance base. Focus the map on your area.": "Masukkan rentang koordinat base aliansi Anda. Fokuskan peta pada area Anda.",
    "Enter the player ID of a linked kingdom member (TC20+) to add as co-editor. Co-editors can manage applications, browse recruit candidates, and update the kingdom profile.": "Masukkan ID pemain anggota kingdom terhubung (TC20+) untuk ditambah sebagai co-editor. Co-editor bisa mengelola lamaran, menjelajahi kandidat rekrut, dan memperbarui profil kingdom.",
    "Every Transfer Event, we open dedicated Discord channels for each kingdom group. Link your account, get auto-assigned to your group, and start coordinating with players in your range — before the event even starts.": "Setiap Transfer Event, kami membuka channel Discord khusus untuk setiap grup kingdom. Hubungkan akun Anda, auto-assign ke grup Anda, dan mulai berkoordinasi dengan pemain di rentang Anda — sebelum event dimulai.",
    "Every active Kingshot gift code in one place. Copy codes and redeem them in-game — never miss free rewards again.": "Semua kode hadiah Kingshot aktif di satu tempat. Salin kode dan tukarkan in-game — tidak pernah lewatkan hadiah gratis lagi.",
    "Every feature exists because R4/R5 leaders asked for it.": "Setiap fitur ada karena pemimpin R4/R5 memintanya.",
    "Every feature exists because R4s and R5s asked for it.": "Setiap fitur ada karena R4 dan R5 memintanya.",
    "Every feature exists because managing prep phase scheduling was a nightmare. Until now.": "Setiap fitur ada karena mengelola jadwal fase prep adalah mimpi buruk. Sampai sekarang.",
    "Every feature exists because rally callers asked for it.": "Setiap fitur ada karena pemanggil rally memintanya.",
    "Every kingdom gets a match percentage based on your profile. Sort by best fit, apply to your top picks, and track your applications.": "Setiap kingdom mendapat persentase kecocokan berdasarkan profil Anda. Urutkan berdasarkan kecocokan terbaik, lamar ke pilihan teratas, dan lacak lamaran Anda.",
    "Every kingdom has an Atlas Score, KvK record, and community reviews. Use filters to narrow it down. Match Scores show how well you fit.": "Setiap kingdom memiliki Skor Atlas, catatan KvK, dan ulasan komunitas. Gunakan filter untuk mempersempit. Skor Kecocokan menunjukkan seberapa cocok Anda.",
    "Every kingdom. Every stat. Searchable, filterable, and ranked. Find exactly what you're looking for in seconds.": "Setiap kingdom. Setiap statistik. Bisa dicari, difilter, dan dirangking. Temukan persis apa yang Anda cari dalam hitungan detik.",
    "Every linked player with TC20+ counts toward your kingdom's colony rank!": "Setiap pemain terhubung dengan TC20+ berkontribusi pada peringkat koloni kingdom Anda!",
    "Every match, every result, every kingdom": "Setiap pertandingan, setiap hasil, setiap kingdom",
    "Every match. Every result. Every streak. Know exactly what you're walking into before the gates open.": "Setiap pertandingan. Setiap hasil. Setiap streak. Ketahui persis apa yang Anda hadapi sebelum gerbang terbuka.",
    "Every player reports their Infantry, Cavalry, and Archer Tier (T1–T11) and Truegold Level (TG1–TG8). Know your kingdom's true military strength.": "Setiap pemain melaporkan Tier Infanteri, Kavaleri, dan Pemanah (T1–T11) dan Level Truegold (TG1–TG8). Ketahui kekuatan militer asli kingdom Anda.",
    "Example: \"{{name}} {{code}}\" — you can remove it after verification.": "Contoh: \"{{name}} {{code}}\" — Anda bisa menghapusnya setelah verifikasi.",
    "Exclusive Consul role in Discord. Recognized voice in the community.": "Peran Consul eksklusif di Discord. Suara yang diakui di komunitas.",
    "Exclusive Discord Channel": "Channel Discord Eksklusif",
    "Exclusive pink role in Discord": "Peran pink eksklusif di Discord",
    "Explain why you believe this decision should be reconsidered.": "Jelaskan mengapa Anda percaya keputusan ini harus dipertimbangkan kembali.",
    "Explore kingdoms and see what's available": "Jelajahi kingdom dan lihat apa yang tersedia",
    "Export the full 3-day schedule as a CSV. Player names, alliances, slot times, and speedup data — ready for Discord or in-game chat.": "Ekspor jadwal 3 hari penuh sebagai CSV. Nama pemain, aliansi, waktu slot, dan data speedup — siap untuk Discord atau chat in-game.",
}
