#!/usr/bin/env python3
"""Generate comprehensive Indonesian translation - Part 10: Final remaining strings."""

T10 = {
    # === prepScheduler remaining ===
    "Stagger enabled — slots shifted to :15/:45 pattern.": "Stagger diaktifkan — slot digeser ke pola :15/:45.",
    "Submission updated.": "Pengiriman diperbarui.",
    "Submission received! Your Prep Manager will assign you a slot.": "Pengiriman diterima! Manajer Prep Anda akan menetapkan slot untuk Anda.",
    "Submission updated!": "Pengiriman diperbarui!",
    "This schedule was created by an unauthorized user and has been removed.": "Jadwal ini dibuat oleh pengguna tidak berwenang dan telah dihapus.",
    "Total": "Total",
    "Type": "Jenis",
    "Unassigned Players — Waitlist": "Pemain Belum Ditetapkan — Daftar Tunggu",
    "Undo": "Urungkan",
    "Update Submission": "Perbarui Pengiriman",
    "Auto-assigned from your linked account": "Otomatis ditetapkan dari akun terhubung Anda",
    "UTC": "UTC",
    "View Form": "Lihat Formulir",
    "View Report": "Lihat Laporan",
    "View Schedule": "Lihat Jadwal",
    "View Screenshot": "Lihat Tangkapan Layar",
    "Schedules you've submitted availability to.": "Jadwal tempat Anda mengirim ketersediaan.",
    "Bio": "Bio",
    "X coordinate must be between 0 and 1199": "Koordinat X harus antara 0 dan 1199",
    "Y coordinate must be between 0 and 1199": "Koordinat Y harus antara 0 dan 1199",
    "Stop guessing. Get deeper insights, unlimited bot commands, and support the platform that helps you win.": "Berhenti menebak. Dapatkan wawasan lebih dalam, perintah bot tak terbatas, dan dukung platform yang membantu Anda menang.",
    "Unlock profile editing and show your in-game stats": "Buka pengeditan profil dan tampilkan statistik in-game Anda",
    "This user profile could not be found or may have been removed.": "Profil pengguna ini tidak ditemukan atau mungkin telah dihapus.",
    "Unable to open subscription management. Please email support@ks-atlas.com for assistance.": "Tidak bisa membuka manajemen langganan. Silakan email support@ks-atlas.com untuk bantuan.",
    "Signed in with {{provider}}": "Masuk dengan {{provider}}",
    "You have full access to Atlas Supporter features. Thanks for backing the project.": "Anda memiliki akses penuh ke fitur Atlas Supporter. Terima kasih telah mendukung proyek ini.",
    "Welcome to Atlas, {{name}}!": "Selamat datang di Atlas, {{name}}!",
    "View Home Kingdom": "Lihat Kingdom Asal",
    "Watchlist": "Daftar Pantau",

    # === quickAction (nested) ===
    "KvK Battle": "KvK Battle",
    "KvK Prep": "KvK Prep",

    # === radarLabels ===
    "Form": "Kondisi",
    "Streaks": "Streak",

    # === rallyCoordinator remaining ===
    "You need Gold Tier access to use the Rally Coordinator.": "Anda memerlukan akses Gold Tier untuk menggunakan Rally Coordinator.",
    "No counter leaders queued": "Tidak ada pemimpin counter dalam antrean",
    "Start by adding allies and enemies with their march times. Then drag them into the Rally or Counter queue.": "Mulai dengan menambah sekutu dan musuh dengan waktu march mereka. Lalu seret ke antrean Rally atau Counter.",
    "No rally leaders yet": "Belum ada pemimpin rally",
    "No rally leaders queued": "Tidak ada pemimpin rally dalam antrean",
    "Hit": "Serangan",
    "Hold to drag": "Tahan untuk seret",
    "Set their march times for each building.": "Atur waktu march mereka untuk setiap bangunan.",
    "Set the hit order — who lands first matters.": "Atur urutan serangan — siapa yang mendarat pertama itu penting.",
    "March": "March",
    "Need {{count}} more to calculate timings.": "Butuh {{count}} lagi untuk menghitung timing.",
    "No presets yet. Build a rally and save it here for instant recall.": "Belum ada preset. Bangun rally dan simpan di sini untuk pemanggilan instan.",
    "Some players have march times over 100s — double-check those values.": "Beberapa pemain memiliki waktu march lebih dari 100d — periksa kembali nilai tersebut.",
    "Counter": "Counter",
    "Rally": "Rally",
    "Use the player pills above to add": "Gunakan pill pemain di atas untuk menambah",
    "KvK BATTLE": "KvK BATTLE",
    "Turn Off": "Matikan",
    "Turn off buff?": "Matikan buff?",

    # === rankings ===
    "Who's dominating? The data doesn't lie.": "Siapa yang mendominasi? Data tidak berbohong.",
    "Top {{count}}": "Top {{count}}",

    # === rateKingdom ===
    "Optional: Share details about your experience...": "Opsional: Bagikan detail tentang pengalaman Anda...",

    # === realtime ===
    "New KvK record for Kingdom {{number}}": "Catatan KvK baru untuk Kingdom {{number}}",

    # === recruiter remaining ===
    "Atlas": "Atlas",
    "External Recruits": "Rekrut Eksternal",
    "Fund depletes ~$5/week starting Feb 23. Current balance sustains the {{tier}} tier for approximately {{weeks}} more weeks. Share the kingdom link to encourage contributions.": "Dana berkurang ~$5/minggu mulai 23 Feb. Saldo saat ini mempertahankan tier {{tier}} selama kurang lebih {{weeks}} minggu lagi. Bagikan tautan kingdom untuk mendorong kontribusi.",
    "Fund Tier Benefits": "Keuntungan Tier Dana",
    "Grace period": "Masa tenggang",
    "Tier Grace Period Active": "Masa Tenggang Tier Aktif",
    "Group": "Grup",
    "From Kingdom": "Dari Kingdom",
    "Min TC": "Min TC",
    "You need to be an active editor for a kingdom to access the Recruiter Dashboard. Claim your kingdom first through the Editor Claiming process.": "Anda perlu menjadi editor aktif untuk kingdom agar bisa mengakses Dasbor Perekrut. Klaim kingdom Anda terlebih dahulu melalui proses Klaim Editor.",
    "Newest First": "Terbaru",
    "No active applications": "Tidak ada lamaran aktif",
    "No active transfer profiles yet": "Belum ada profil transfer aktif",
    "No Active Editor Role": "Tidak Ada Peran Editor Aktif",
    "No approved applications": "Tidak ada lamaran disetujui",
    "No Changes": "Tidak Ada Perubahan",
    "No co-editors yet. Invite up to 5 co-editors to help manage your kingdom.": "Belum ada co-editor. Undang hingga 5 co-editor untuk membantu mengelola kingdom Anda.",
    "No contributions yet. Share the contribution link with your kingdom members!": "Belum ada kontribusi. Bagikan tautan kontribusi dengan anggota kingdom Anda!",
    "Track recruits from outside Atlas here": "Lacak rekrut dari luar Atlas di sini",
    "No invites remaining": "Tidak ada undangan tersisa",
    "No Kingdom Fund Yet": "Belum Ada Kingdom Fund",
    "No applications match your search": "Tidak ada lamaran yang sesuai pencarian",
    "No past applications": "Tidak ada lamaran sebelumnya",
    "No status changes yet": "Belum ada perubahan status",
    "No transactions yet. Share the contribution link with your kingdom members!": "Belum ada transaksi. Bagikan tautan kontribusi dengan anggota kingdom Anda!",
    "No recruit candidates match your filters": "Tidak ada kandidat rekrut yang sesuai filter",
    "Note (optional)": "Catatan (opsional)",
    "Only the primary editor can invite co-editors.": "Hanya editor utama yang bisa mengundang co-editor.",
    "Save Profile Changes": "Simpan Perubahan Profil",
    "Search applicants...": "Cari pelamar...",
    "Send Invites": "Kirim Undangan",
    "Showing players in your transfer group": "Menampilkan pemain di grup transfer Anda",
    "Oldest": "Terlama",
    "Start a Kingdom Fund to unlock tier benefits and boost your listing visibility.": "Mulai Kingdom Fund untuk membuka keuntungan tier dan meningkatkan visibilitas daftar.",
    "Start a Kingdom Fund to edit your listing profile": "Mulai Kingdom Fund untuk mengedit profil daftar Anda",
    "Transfer Status History": "Riwayat Status Transfer",
    "Toggle on to appear in transfer searches": "Aktifkan untuk muncul di pencarian transfer",
    "Total In": "Total Masuk",
    "Total Out": "Total Keluar",
    "Transactions": "Transaksi",
    "Try adjusting your filters to broaden results.": "Coba sesuaikan filter untuk memperluas hasil.",
    "Upgrade to Bronze+ to view full profile details": "Upgrade ke Perunggu+ untuk melihat detail profil lengkap",
    "Upgrade to Silver+ to send invites": "Upgrade ke Silver+ untuk mengirim undangan",
    "Username *": "Username *",
    "Weekly maintenance": "Pemeliharaan mingguan",

    # === prepScheduler deep remaining ===
    "Day": "Hari",
    "Buff Type": "Jenis Buff",
    "No submissions yet": "Belum ada pengiriman",
    "Archive Schedule": "Arsipkan Jadwal",
    "Delete Schedule": "Hapus Jadwal",
    "Close Form": "Tutup Formulir",
    "Reopen Form": "Buka Kembali Formulir",
    "Add Manager": "Tambah Manajer",
    "Remove Manager": "Hapus Manajer",
    "View Submissions": "Lihat Pengiriman",
    "Copy Form Link": "Salin Tautan Formulir",
    "Form Link Copied!": "Tautan Formulir Tersalin!",
    "No schedule found.": "Jadwal tidak ditemukan.",
    "Schedule not found or you don't have permission.": "Jadwal tidak ditemukan atau Anda tidak memiliki izin.",
    "Create Schedule": "Buat Jadwal",
    "My Schedules": "Jadwal Saya",
    "Active Schedules": "Jadwal Aktif",
    "Archived Schedules": "Jadwal Diarsipkan",
    "No active schedules.": "Tidak ada jadwal aktif.",
    "No archived schedules.": "Tidak ada jadwal diarsipkan.",
    "Share this link with your kingdom players:": "Bagikan tautan ini dengan pemain kingdom Anda:",
    "Players submit their speedups, availability, and proof.": "Pemain mengirim speedup, ketersediaan, dan bukti mereka.",
    "Manager can review and assign slots.": "Manajer bisa meninjau dan menetapkan slot.",
    "All times are in UTC.": "Semua waktu dalam UTC.",

    # === prepLanding remaining ===
    "Right now, your Prep Manager is probably juggling a Google Sheet, a Discord thread that's 500 messages deep, and a headache. Players post their availability in different time zones. Nobody knows who has the best speedups. Half the kingdom forgets to respond.": "Saat ini, Manajer Prep Anda mungkin sedang berjuang dengan Google Sheet, thread Discord yang 500 pesan panjangnya, dan sakit kepala. Pemain memposting ketersediaan di zona waktu berbeda. Tidak ada yang tahu siapa yang punya speedup terbaik. Setengah kingdom lupa merespons.",
    "Unassigned players get flagged immediately. Empty time slots are highlighted. The manager sees exactly where the gaps are and can manually assign anyone into any slot with override.": "Pemain yang belum ditetapkan ditandai langsung. Slot waktu kosong disorot. Manajer melihat persis di mana celahnya dan bisa menetapkan siapa pun ke slot mana pun dengan override.",

    # === More single-word/short strings that appear as nested values ===
    "Edit": "Edit",
    "Preview": "Pratinjau",
    "Save Changes": "Simpan Perubahan",
    "Saved": "Tersimpan",
    "Saving...": "Menyimpan...",
    "Sending...": "Mengirim...",
    "Working...": "Memproses...",
    "Creating...": "Membuat...",
    "Deleting...": "Menghapus...",
    "Archiving...": "Mengarsipkan...",
    "Locking...": "Mengunci...",
    "Unlocking...": "Membuka kunci...",
    "Assigning...": "Menetapkan...",
    "Clearing...": "Menghapus...",
    "Notifying...": "Memberitahu...",
    "Processing...": "Memproses...",

    # profile nested
    "Complete Profile": "Lengkapi Profil",
    "Town Center": "Town Center",
    "Kingdom": "Kingdom",

    # admin catch-all
    "Approve": "Setujui",
    "Decline": "Tolak",
    "Delete": "Hapus",
    "Pending": "Tertunda",
    "Rejected": "Ditolak",
    "Approved": "Disetujui",
    "Processing": "Memproses",
    "Admin Panel": "Panel Admin",
    "Admin access": "Akses admin",

    # misc remaining
    "Active Referrers": "Perujuk Aktif",
    "Conversion Rate": "Tingkat Konversi",
    "Health Metrics": "Metrik Kesehatan",
    "Source Comparison": "Perbandingan Sumber",
    "Atlas Archivist role for top contributors": "Peran Atlas Archivist untuk kontributor teratas",
    "Community Reviews": "Ulasan Komunitas",
    "Community reviews from players": "Ulasan komunitas dari pemain",
    "Featured Review": "Ulasan Unggulan",
    "Harassment": "Pelecehan",
    "Highest Rated": "Rating Tertinggi",
    "Reviews:": "Ulasan:",
    "Newest": "Terbaru",
    "Write a reply...": "Tulis balasan...",
    "Sign in to review": "Masuk untuk mengulas",
    "Sort by:": "Urutkan berdasarkan:",
    "View More": "Lihat Lebih",
    "Score Components": "Komponen Skor",
    "Show {{count}} More": "Tampilkan {{count}} Lagi",
    "No kingdoms match \"{{query}}\"": "Tidak ada kingdom yang cocok \"{{query}}\"",
    "Search by kingdom number (e.g., 1001)...": "Cari berdasarkan nomor kingdom (mis., 1001)...",
    "Score history is being calculated. Check back soon.": "Riwayat skor sedang dihitung. Periksa kembali segera.",
    "What is Combined Power Level?": "Apa itu Level Kekuatan Gabungan?",
    "Submissions are closed for this KvK season.": "Pengiriman ditutup untuk musim KvK ini.",
    "Score Timing": "Waktu Skor",
    "Select a season": "Pilih musim",
    "Get Embed Code": "Dapatkan Kode Embed",
    "Scan to open on mobile": "Pindai untuk buka di mobile",
    "Share Image": "Bagikan Gambar",
    "Share...": "Bagikan...",
    "Share {{type}}": "Bagikan {{type}}",
    "Shared!": "Dibagikan!",
    "Sharing...": "Membagikan...",
    "Show QR Code": "Tampilkan Kode QR",
    "How it works": "Cara kerjanya",
    "Nearby Kingdoms": "Kingdom Terdekat",
    "See how wins and losses affect your score": "Lihat bagaimana kemenangan dan kekalahan mempengaruhi skor Anda",
    "Understand the scoring formula": "Pahami rumus penilaian",
    "Form Bonus": "Bonus Kondisi",
    "See how your next KvK results could change your Atlas Score": "Lihat bagaimana hasil KvK berikutnya bisa mengubah Skor Atlas Anda",
    "Reset": "Reset",
    "Sign in to unlock the Score Simulator": "Masuk untuk membuka Simulator Skor",
    "Simulate Next KvK": "Simulasikan KvK Berikutnya",
    "Streak Impact": "Dampak Streak",
    "Unlock Simulator": "Buka Simulator",
    "Not everyone can donate, and that's totally fine! Here's how you can still help:": "Tidak semua orang bisa berdonasi, dan itu tidak masalah! Begini cara Anda tetap bisa membantu:",
    "Full KvK History": "Riwayat KvK Lengkap",
    "See where every kingdom stands": "Lihat posisi setiap kingdom",
    "Full stats and performance history": "Statistik lengkap dan riwayat performa",
    "Want to give more? You can increase your amount in the Stripe portal after subscribing.": "Ingin memberi lebih? Anda bisa menambah jumlah di portal Stripe setelah berlangganan.",
    "Note: One-time donations don't include the Supporter badge or Discord role.": "Catatan: Donasi satu kali tidak termasuk lencana Supporter atau peran Discord.",
    "Full access to the Rally Coordinator — plan rallies, track marches, coordinate hits": "Akses penuh ke Rally Coordinator — rencanakan rally, lacak march, koordinasikan serangan",
    "Unlimited /multirally and premium Discord bot commands (free: 5/day)": "/multirally tak terbatas dan perintah bot Discord premium (gratis: 5/hari)",
    "Unlimited Bot Commands": "Perintah Bot Tak Terbatas",
    "First to try new features before public release": "Pertama mencoba fitur baru sebelum rilis publik",
    "Gift Code Bulk Redeem": "Redeem Massal Kode Hadiah",
    "Show Columns": "Tampilkan Kolom",
    "S Tier - Elite (Top 10%)": "S Tier - Elite (Top 10%)",
    "We're building what the community needs. Drop your suggestions in Discord.": "Kami membangun apa yang dibutuhkan komunitas. Kirimkan saran Anda di Discord.",
    "Time your rallies to land together. Set hit order, march times, and delay windows — so your alliance strikes as one.": "Atur timing rally agar mendarat bersamaan. Atur urutan serangan, waktu march, dan jendela delay — agar aliansi Anda menyerang sebagai satu kesatuan.",
    "Find your next kingdom — or find the right players. Browse listings, create a transfer profile, and apply directly. No more blind transfers.": "Temukan kingdom berikutnya — atau temukan pemain yang tepat. Jelajahi daftar, buat profil transfer, dan lamar langsung. Tidak ada lagi transfer buta.",
    "Select \"I'm Transferring\" from the toggle at the top. This unlocks tools built for you.": "Pilih \"Saya Transfer\" dari toggle di atas. Ini membuka alat yang dibangun untuk Anda.",
    "Set your power, TC level, language, and what you're looking for. Kingdoms see this when you apply.": "Atur kekuatan, level TC, bahasa, dan apa yang Anda cari. Kingdom melihat ini saat Anda melamar.",
    "Found the right one? Hit Apply. You can have up to 3 active applications. Track their status in My Applications.": "Menemukan yang tepat? Klik Lamar. Anda bisa memiliki hingga 3 lamaran aktif. Lacak statusnya di Lamaran Saya.",
    "Open the Recruiter Dashboard. Add your pitch, requirements, languages, vibe tags, and event times. This is your kingdom's storefront.": "Buka Dasbor Perekrut. Tambahkan pitch, persyaratan, bahasa, tag suasana, dan waktu event. Ini adalah etalase kingdom Anda.",
    "Set up your listing": "Atur daftar Anda",
    "Fund your listing (optional)": "Danai daftar Anda (opsional)",
    "To recruit for your kingdom, you need to link your in-game account first. This tells us which kingdom you represent.": "Untuk merekrut untuk kingdom Anda, Anda perlu menghubungkan akun in-game terlebih dahulu. Ini memberi tahu kami kingdom mana yang Anda wakili.",
    "Sign in and link your Kingshot account to claim your kingdom, set up your listing, and review transfer applications.": "Masuk dan hubungkan akun Kingshot untuk klaim kingdom, atur daftar, dan tinjau lamaran transfer.",
    "Whether you're looking for a new home or looking for strong players — the Transfer Hub connects you with the right match. No cost, no catch.": "Apakah Anda mencari rumah baru atau mencari pemain kuat — Transfer Hub menghubungkan Anda dengan kecocokan yang tepat. Tanpa biaya, tanpa jebakan.",
    "Optionally deposit into your kingdom's fund to unlock priority placement, invite features, and a premium badge. Anyone in your kingdom can contribute.": "Opsional deposit ke dana kingdom Anda untuk membuka penempatan prioritas, fitur undangan, dan lencana premium. Siapa pun di kingdom Anda bisa berkontribusi.",
    "See which kingdoms are actively recruiting — with Atlas Scores, KvK records, and community reviews. No more guessing.": "Lihat kingdom mana yang aktif merekrut — dengan Skor Atlas, catatan KvK, dan ulasan komunitas. Tidak perlu menebak lagi.",
    "Recruiters will see your username and kingdom of origin.": "Perekrut akan melihat username dan kingdom asal Anda.",
    "Recruiter badge on your profile. Highlighted in kingdom player lists.": "Lencana perekrut di profil Anda. Disorot di daftar pemain kingdom.",
    "Scores reflect each kingdom's Atlas Score before the battle began—based on their track record up to that point. No hindsight, just raw pre-battle power.": "Skor mencerminkan Skor Atlas setiap kingdom sebelum pertempuran dimulai—berdasarkan rekam jejak hingga titik itu. Tanpa melihat ke belakang, hanya kekuatan mentah pra-pertempuran.",
    "Submissions are reviewed before being applied. False reports may affect your reputation score.": "Pengiriman ditinjau sebelum diterapkan. Laporan palsu bisa mempengaruhi skor reputasi Anda.",
    "Suggested value is same as current value": "Nilai yang disarankan sama dengan nilai saat ini",
    "This kingdom qualifies for Google rich results rating badge": "Kingdom ini memenuhi syarat untuk lencana rating Google rich results",
    "No reviews yet. Be the first to share your experience!": "Belum ada ulasan. Jadilah yang pertama berbagi pengalaman!",
    "Showing {{visible}} of {{total}}": "Menampilkan {{visible}} dari {{total}}",
    "Win": "Menang",
    "Mute this chat": "Bisukan chat ini",
    "Unmute this chat": "Bunyikan chat ini",
    "Get notified when someone requests to be a co-editor for your kingdom": "Dapatkan notifikasi saat seseorang meminta jadi co-editor untuk kingdom Anda",
    "Active Listings": "Daftar Aktif",
    "All Applications": "Semua Lamaran",
    "Inbox": "Kotak Masuk",
    "Kingdom Profile": "Profil Kingdom",
    "Listing Settings": "Pengaturan Daftar",
    "Recruiter Dashboard": "Dasbor Perekrut",
    "Tier grace period active — contribute to maintain the current tier before {{date}}": "Masa tenggang tier aktif — kontribusi untuk mempertahankan tier saat ini sebelum {{date}}",
    "Showing {{count}} of {{total}} KvKs": "Menampilkan {{count}} dari {{total}} KvK",
    "Score {{change}} since your last visit": "Skor {{change}} sejak kunjungan terakhir Anda",
    "Calculate smarter. Grow faster.": "Hitung lebih cerdas. Tumbuh lebih cepat.",

    # Welcome toast with emoji
    "Welcome to Atlas, {{name}}! 🌍": "Selamat datang di Atlas, {{name}}! 🌍",

    # remaining botDashboard nested
    "Only the server owner can block users.": "Hanya pemilik server yang bisa memblokir pengguna.",
    "Only the server owner can remove servers.": "Hanya pemilik server yang bisa menghapus server.",
    "Owned by": "Dimiliki oleh",
    "Paste a Discord User ID (18-digit number).": "Tempel ID Pengguna Discord (angka 18 digit).",
    "Reaction Role Panel": "Panel Peran Reaksi",
    "Remove this server?": "Hapus server ini?",
    "Role name": "Nama peran",
    "Select a server to configure.": "Pilih server untuk dikonfigurasi.",
    "Select server": "Pilih server",
    "Server removed.": "Server dihapus.",
    "Send a DM reminder": "Kirim pengingat DM",
    "Tap an emoji to pick a role": "Ketuk emoji untuk memilih peran",
    "This is the only server you manage.": "Ini satu-satunya server yang Anda kelola.",
    "Update Message": "Perbarui Pesan",
    "User ID": "ID Pengguna",
    "You are the owner": "Anda adalah pemilik",
    "You must deploy first.": "Anda harus deploy terlebih dahulu.",
    "Auto-post new gift codes": "Auto-post kode hadiah baru",
    "Auto-saves": "Otomatis tersimpan",
    "BLOCK A USER": "BLOKIR PENGGUNA",
    "BLOCKED USERS": "PENGGUNA DIBLOKIR",
    "Set reminder channel.": "Atur channel pengingat.",
    "GENERAL SETTINGS": "PENGATURAN UMUM",
    "Get Reminded": "Dapatkan Pengingat",
    "GIFT CODE CHANNEL": "CHANNEL KODE HADIAH",
    "Auto-post new gift codes to your server": "Auto-post kode hadiah baru ke server Anda",
    "How to fix": "Cara memperbaiki",
    "No deployed message to edit.": "Tidak ada pesan yang dideploy untuk diedit.",
    "User has no Discord linked.": "Pengguna tidak memiliki Discord terhubung.",
    "+ Server": "+ Server",
    "Server already registered.": "Server sudah terdaftar.",

    # battle registry remaining
    "Your Kingdom Has an Active Battle Registry": "Kingdom Anda Memiliki Battle Registry Aktif",
    "GOLD & SILVER TIER KINGDOMS": "KINGDOM GOLD & SILVER TIER",
    "Only Editors, Co-Editors, and Battle Managers can create registries. Ask your kingdom leadership for access.": "Hanya Editor, Co-Editor, dan Battle Manager yang bisa membuat registrasi. Minta akses ke kepemimpinan kingdom Anda.",
    "Only Editors, Co-Editors, and Battle Managers can create registries.": "Hanya Editor, Co-Editor, dan Battle Manager yang bisa membuat registrasi.",
    "Only Silver Tier and above kingdoms can use the KvK Battle Registry.": "Hanya kingdom Silver Tier ke atas yang bisa menggunakan KvK Battle Registry.",
    "For each troop type, select your highest Tier (T8–T11) and Truegold Level (TG0–TG8). Leave blank if you don't use that troop type.": "Untuk setiap jenis pasukan, pilih Tier tertinggi (T8–T11) dan Level Truegold (TG0–TG8). Kosongkan jika Anda tidak menggunakan jenis pasukan itu.",
    "Update Player": "Perbarui Pemain",
    "Auto-filled from your profile.": "Otomatis diisi dari profil Anda.",
    "To": "Ke",
    "Create a Battle Registry for your Silver+ Tier kingdom. Share the link with players so they can register their availability and troop levels for the upcoming castle battle.": "Buat Battle Registry untuk kingdom Silver+ Tier Anda. Bagikan tautan ke pemain agar mereka bisa mendaftar ketersediaan dan level pasukan untuk castle battle mendatang.",

    # battleRegistryLanding remaining
    "You have full access as a Gold/Silver Tier kingdom member.": "Anda memiliki akses penuh sebagai anggota kingdom Gold/Silver Tier.",
    "You have full access to the Battle Registry.": "Anda memiliki akses penuh ke Battle Registry.",
    "Only your kingdom's players can register. Editors, Co-Editors, and Battle Managers control the registry. Your data stays yours.": "Hanya pemain kingdom Anda yang bisa mendaftar. Editor, Co-Editor, dan Battle Manager mengontrol registrasi. Data Anda tetap milik Anda.",
    "See exactly how many players each alliance is contributing. Hold everyone accountable. Reward the alliances that show up.": "Lihat persis berapa banyak pemain yang dikontribusikan setiap aliansi. Buat semua bertanggung jawab. Beri penghargaan aliansi yang hadir.",
    "Share a single link with your kingdom. Players fill a 30-second form. Username and alliance auto-fill. Zero friction, maximum intel.": "Bagikan satu tautan dengan kingdom Anda. Pemain mengisi formulir 30 detik. Username dan aliansi otomatis terisi. Tanpa gesekan, intelijen maksimal.",
    "Players pick their availability between 12:00–18:00 UTC. Instantly see how many warriors you have at each hour. No more guessing who's online.": "Pemain memilih ketersediaan antara 12:00–18:00 UTC. Langsung lihat berapa banyak prajurit Anda di setiap jam. Tidak perlu menebak siapa yang online.",
    "Gold & Silver Tier Kingdom Feature": "Fitur Kingdom Gold & Silver Tier",
    "Available for Gold & Silver Tier kingdoms. Contribute to the Kingdom Fund to unlock.": "Tersedia untuk kingdom Gold & Silver Tier. Kontribusi ke Kingdom Fund untuk membuka.",
    "Share the link. Players fill out their time slot, troop tiers, and truegold levels in 30 seconds.": "Bagikan tautan. Pemain mengisi slot waktu, tier pasukan, dan level truegold dalam 30 detik.",
    "Use the dashboard to see who's available, what they're bringing, and plan your castle hit accordingly.": "Gunakan dasbor untuk melihat siapa yang tersedia, apa yang mereka bawa, dan rencanakan serangan castle sesuai.",
    "View the Registry": "Lihat Registrasi",
}
