#!/usr/bin/env python3
"""Generate comprehensive Indonesian translation - Part 2: H-R."""

T2 = {
    # === H ===
    "HOW IT": "CARA",
    "WORKS": "KERJA",
    "Hot Right Now": "Sedang Populer",
    "How to get access": "Cara mendapatkan akses",
    "hours": "jam",
    "minutes": "menit",
    "seconds": "detik",

    # === I ===
    "I Changed My Name — Verify": "Saya Sudah Ganti Nama — Verifikasi",
    "I don't need a buff slot": "Saya tidak butuh slot buff",
    "I'm Browsing": "Saya Menjelajah",
    "I'm Recruiting": "Saya Merekrut",
    "I'm Transferring": "Saya Transfer",
    "I'm looking for a new kingdom": "Saya mencari kingdom baru",
    "I'm recruiting for my kingdom": "Saya merekrut untuk kingdom saya",
    "If the fund reaches a new tier, the listing upgrades": "Jika dana mencapai tier baru, daftar akan upgrade",
    "Image copied!": "Gambar tersalin!",
    "Image must be under 5MB.": "Gambar harus di bawah 5MB.",
    "In the Raffle": "Dalam Undian",
    "Inappropriate content": "Konten tidak pantas",
    "Instructions for your kingdom members...": "Instruksi untuk anggota kingdom Anda...",
    "Interval between hits": "Interval antar serangan",
    "Invalid Rate": "Rate Tidak Valid",
    "Invite Budget": "Anggaran Undangan",
    "Invite Co-Editor": "Undang Co-Editor",

    # === J ===
    "Join Discord Server": "Gabung Server Discord",
    "Join the Atlas Discord": "Gabung Atlas Discord",
    "Join the Discussion": "Gabung Diskusi",
    "Jump into the designer and start planning your alliance fortress.": "Masuk ke desainer dan mulai merencanakan benteng aliansi Anda.",
    "Just browsing": "Hanya menjelajah",
    "Just now": "Baru saja",

    # === K ===
    "KINGDOM LEADERS": "PEMIMPIN KINGDOM",
    "Keep dominating to maintain S-Tier": "Terus dominasi untuk mempertahankan S-Tier",
    "Keyboard & Trackpad": "Keyboard & Trackpad",
    "Kingdom A": "Kingdom A",
    "Kingdom B": "Kingdom B",
    "Kingdom Bio & Language display": "Tampilan Bio & Bahasa Kingdom",
    "Kingdom Editors & Co-Editors": "Editor & Co-Editor Kingdom",
    "Kingdom Players": "Pemain Kingdom",
    "Kingdom Policies & Vibe tags": "Kebijakan & Tag Suasana Kingdom",
    "Kingdom Ranking History": "Riwayat Peringkat Kingdom",
    "Kingdom Settlers Campaign #1": "Kampanye Kingdom Settlers #1",
    "Kingdom Vibe": "Suasana Kingdom",
    "Kingdom:": "Kingdom:",
    "KvK": "KvK",
    "KvK #": "KvK #",
    "KvK Avail.": "Ketersediaan KvK",
    "KvK Battle": "KvK Battle",
    "KvK Battle Planner": "KvK Battle Planner",
    "KvK Battle Planner access": "Akses KvK Battle Planner",
    "KvK Battle Registry access": "Akses KvK Battle Registry",
    "KvK Number (optional)": "Nomor KvK (opsional)",
    "KvK Prep": "KvK Prep",
    "KvK Prep Scheduler access": "Akses Jadwal Prep KvK",
    "KvK Battle Planner is HERE": "KvK Battle Planner sudah HADIR",

    # === L ===
    "Label (optional)": "Label (opsional)",
    "Last 30 Days": "30 Hari Terakhir",
    "Last reminder": "Pengingat terakhir",
    "Launch the Planner": "Buka Planner",
    "Leading": "Leading",
    "Learn More →": "Pelajari Lebih →",
    "Link Account to Submit": "Hubungkan Akun untuk Mengirim",
    "Link Copied!": "Tautan Tersalin!",
    "Link Discord": "Hubungkan Discord",
    "Link Discord →": "Hubungkan Discord →",
    "Link Failed": "Hubungan Gagal",
    "Link Kingshot": "Hubungkan Kingshot",
    "Link Kingshot Account": "Hubungkan Akun Kingshot",
    "Link Your Discord": "Hubungkan Discord Anda",
    "Link Your Kingshot Account": "Hubungkan Akun Kingshot Anda",
    "Link Your Kingshot Account First": "Hubungkan Akun Kingshot Terlebih Dahulu",
    "Link account for more": "Hubungkan akun untuk lebih banyak",
    "Link your Discord account in your profile first.": "Hubungkan akun Discord di profil Anda terlebih dahulu.",
    "Link your Discord account on Atlas": "Hubungkan akun Discord Anda di Atlas",
    "Link your Kingshot account first to become a co-editor.": "Hubungkan akun Kingshot terlebih dahulu untuk menjadi co-editor.",
    "Link your Kingshot account first to endorse.": "Hubungkan akun Kingshot terlebih dahulu untuk mendukung.",
    "Link your Kingshot account first, then claim your kingdom.": "Hubungkan akun Kingshot terlebih dahulu, lalu klaim kingdom Anda.",
    "Link your Kingshot account to apply for transfers and access all Transfer Hub features.": "Hubungkan akun Kingshot untuk melamar transfer dan mengakses semua fitur Transfer Hub.",
    "Link your Kingshot account to claim your kingdom.": "Hubungkan akun Kingshot untuk klaim kingdom Anda.",
    "Link your Kingshot account to compare up to 5 kingdoms": "Hubungkan akun Kingshot untuk membandingkan hingga 5 kingdom",
    "Link your Kingshot account to submit KvK results.": "Hubungkan akun Kingshot untuk mengirim hasil KvK.",
    "Link your Kingshot account to verify your kingdom and endorse.": "Hubungkan akun Kingshot untuk memverifikasi kingdom dan mendukung.",
    "Link your account": "Hubungkan akun Anda",
    "Link your account to see personalized transfer matches": "Hubungkan akun Anda untuk melihat kecocokan transfer yang dipersonalisasi",
    "Link your account to submit KvK results and earn contributor status.": "Hubungkan akun Anda untuk mengirim hasil KvK dan mendapat status kontributor.",
    "Link your kingdom for auto-filter": "Hubungkan kingdom Anda untuk auto-filter",
    "Linked Accounts": "Akun Terhubung",
    "Linked Kingshot account": "Akun Kingshot terhubung",
    "Listing link copied! Share to find recruit candidates.": "Tautan daftar tersalin! Bagikan untuk menemukan kandidat rekrut.",
    "Live Draw In": "Undian Langsung Dalam",
    "Live buff timers with auto-expire alerts": "Timer buff langsung dengan peringatan kadaluarsa otomatis",
    "Load More": "Muat Lebih",
    "Loading applications...": "Memuat lamaran...",
    "Loading chart...": "Memuat grafik...",
    "Loading dashboard...": "Memuat dasbor...",
    "Loading endorsement details...": "Memuat detail dukungan...",
    "Loading endorsements...": "Memuat dukungan...",
    "Loading more kingdoms...": "Memuat kingdom lainnya...",
    "Loading more...": "Memuat lebih...",
    "Loading players...": "Memuat pemain...",
    "Loading ranking history...": "Memuat riwayat peringkat...",
    "Loading recruit candidates...": "Memuat kandidat rekrut...",
    "Loading reviews...": "Memuat ulasan...",
    "Loading score history...": "Memuat riwayat skor...",
    "Loading users...": "Memuat pengguna...",
    "Local Time": "Waktu Lokal",
    "Log in to share designs": "Masuk untuk membagikan desain",
    "Log in with your game account": "Masuk dengan akun game Anda",
    "Long-press a player to edit or remove": "Tekan lama pemain untuk edit atau hapus",
    "Looking to transfer or recruit?": "Ingin transfer atau merekrut?",
    "Lowest Rated": "Rating Terendah",

    # === M ===
    "Manage Alliance Event Reminders and Gift Codes.": "Kelola Pengingat Event Aliansi dan Kode Hadiah.",
    "Manage bot settings across multiple Discord servers.": "Kelola pengaturan bot di beberapa server Discord.",
    "Manage your kingdom listing and review applications": "Kelola daftar kingdom dan tinjau lamaran",
    "Map Area Focus": "Fokus Area Peta",
    "March": "March",
    "Match Breakdown": "Rincian Kecocokan",
    "Match Score (Best → Worst)": "Skor Kecocokan (Terbaik → Terburuk)",
    "Member since": "Anggota sejak",
    "Memory Warnings": "Peringatan Memori",
    "Message (optional)": "Pesan (opsional)",
    "Message ID": "ID Pesan",
    "Message queued — will send when back online": "Pesan diantrean — akan dikirim saat kembali online",
    "Message updated in Discord!": "Pesan diperbarui di Discord!",
    "Min 1 player": "Min 1 pemain",
    "Min Atlas Score": "Min Skor Atlas",
    "Min Match Score": "Min Skor Kecocokan",
    "Min Power": "Min Kekuatan",
    "Min Power (in Millions)": "Min Kekuatan (dalam Jutaan)",
    "Min TC": "Min TC",
    "Min TC & Power requirements shown": "Persyaratan Min TC & Kekuatan ditampilkan",
    "Min TC Level": "Min Level TC",
    "Misleading information": "Informasi menyesatkan",
    "Missing required fields": "Kolom wajib belum diisi",
    "More Actions": "Aksi Lainnya",
    "More Details": "Detail Lebih",
    "More ways to support Atlas — coming soon": "Lebih banyak cara mendukung Atlas — segera hadir",
    "Multi-Compare — Up to 5 kingdoms side-by-side": "Multi-Bandingkan — Hingga 5 kingdom berdampingan",
    "Multi-Server Management": "Manajemen Multi-Server",
    "Multi-rally strike coordination with precise timing": "Koordinasi serangan multi-rally dengan timing presisi",

    # === N ===
    "NEW": "BARU",
    "Navigate": "Navigasi",
    "No data for this kingdom yet.": "Belum ada data untuk kingdom ini.",
    "No entries yet": "Belum ada entri",
    "No saved designs.": "Tidak ada desain tersimpan.",
    "None": "Tidak Ada",
    "Not Qualified": "Tidak Memenuhi Syarat",
    "Not Recruiting": "Tidak Merekrut",
    "Notes": "Catatan",
    "Nothing to report": "Tidak ada yang dilaporkan",

    # === O ===
    "Open Planner": "Buka Planner",
    "Open Registration Form": "Buka Formulir Registrasi",
    "Open the Scheduler": "Buka Penjadwal",
    "Organize Your Kingdom's Prep Phase": "Organisir Fase Prep Kingdom Anda",
    "Ownership verified!": "Kepemilikan terverifikasi!",

    # === P ===
    "Paste the gift code": "Tempel kode hadiah",
    "Pending Change Requests": "Permintaan Perubahan Tertunda",
    "Pending Editor Claim": "Klaim Editor Tertunda",
    "Pick your mode": "Pilih mode Anda",
    "Pink badge on your profile": "Lencana pink di profil Anda",
    "Place Banners or HQ First": "Tempatkan Banner atau HQ Terlebih Dahulu",
    "Plan your path to the next tier": "Rencanakan jalur ke tier berikutnya",
    "Player Bio": "Bio Pemain",
    "Player Name": "Nama Pemain",
    "Player data refreshed!": "Data pemain diperbarui!",
    "Player entry updated.": "Entri pemain diperbarui.",
    "Player name": "Nama pemain",
    "Players *": "Pemain *",
    "Players in Atlas": "Pemain di Atlas",
    "Power (High → Low)": "Kekuatan (Tinggi → Rendah)",
    "Power (High)": "Kekuatan (Tinggi)",
    "Power (M)": "Kekuatan (M)",
    "Pre-Transfer": "Pra-Transfer",
    "Predict Your Future Score": "Prediksi Skor Masa Depan Anda",
    "Prep L": "Kalah Prep",
    "Prep Managers": "Manajer Prep",
    "Prep Scheduler": "Jadwal Prep",
    "Prep W": "Menang Prep",
    "Prep Win": "Menang Prep",
    "Preparation Phase": "Fase Persiapan",
    "Priority placement at the top": "Penempatan prioritas di atas",
    "Priority placement in searches": "Penempatan prioritas dalam pencarian",
    "Projected Score": "Skor Proyeksi",
    "Put any kingdoms in the ring. Let the stats decide.": "Adu kingdom mana pun. Biarkan statistik yang memutuskan.",
    "QR Code": "Kode QR",
    "QR Code shown!": "Kode QR ditampilkan!",
    "Qualified": "Memenuhi Syarat",
    "Qualifying": "Memenuhi Syarat",
    "Quick tip": "Tip cepat",

    # === R ===
    "RALLY LEADERS": "PEMIMPIN RALLY",
    "REACTION ROLES": "PERAN REAKSI",
    "REFERENCE DATE": "TANGGAL REFERENSI",
    "REMIND BEFORE": "INGATKAN SEBELUM",
    "REMINDER CHANNEL": "CHANNEL PENGINGAT",
    "REMINDER HISTORY": "RIWAYAT PENGINGAT",
    "ROLE TO MENTION": "PERAN UNTUK DIMENTION",
    "Rally timeline appears here once you queue 2+ players": "Timeline rally muncul di sini setelah Anda antreankan 2+ pemain",
    "Rally your kingdom to climb the ranks": "Ajak kingdom Anda untuk naik peringkat",
    "Rank (Best → Worst)": "Peringkat (Terbaik → Terburuk)",
    "Ranks better than": "Peringkat lebih baik dari",
    "Rating:": "Penilaian:",
    "Re-deploy": "Deploy Ulang",
    "Reach Gold Tier": "Capai Gold Tier",
    "Reach Silver": "Capai Silver",
    "Read-only access — we only fetch your public profile (name, avatar, kingdom)": "Akses baca-saja — kami hanya mengambil profil publik Anda (nama, avatar, kingdom)",
    "Ready to organize your kingdom?": "Siap mengorganisir kingdom Anda?",
    "Real data. Real applications. Zero guesswork.": "Data nyata. Lamaran nyata. Tanpa tebak-tebakan.",
    "Recent Referrals": "Referral Terbaru",
    "Recommended for You": "Direkomendasikan untuk Anda",
    "Recruit Candidates": "Kandidat Rekrut",
    "Recruiters": "Perekrut",
    "Recruitment Tag": "Tag Rekrutmen",
    "Redeem on Kingshot Website": "Tukarkan di Situs Kingshot",
    "Referred": "Direferensikan",
    "Referrer": "Perujuk",
    "Refresh Data": "Perbarui Data",
    "Refresh failed": "Gagal memperbarui",
    "Refreshing...": "Memperbarui...",
    "Register Now": "Daftar Sekarang",
    "Registration failed": "Registrasi gagal",
    "Registration submitted!": "Registrasi terkirim!",
    "Registration updated!": "Registrasi diperbarui!",
    "Registry closed.": "Registrasi ditutup.",
    "Registry reopened.": "Registrasi dibuka kembali.",
    "Report Review": "Laporkan Ulasan",
    "Request Co-Editor": "Minta Co-Editor",
    "Request Slot Change": "Minta Perubahan Slot",
    "Request Type": "Jenis Permintaan",
    "Request a Change": "Minta Perubahan",
    "Request just sent! The editor has been notified.": "Permintaan terkirim! Editor telah diberitahu.",
    "Requesting...": "Meminta...",
    "Restarts": "Restart",
    "Review applications": "Tinjau lamaran",
}
