#!/usr/bin/env python3
"""Generate comprehensive Indonesian translation - Part 9: All remaining nested/prefixed strings."""

T9 = {
    # === baseDesigner (nested keys - need exact English values) ===
    "Shared design not found.": "Desain bersama tidak ditemukan.",
    "This link may have expired or been removed.": "Tautan ini mungkin telah kadaluarsa atau dihapus.",
    "Select building types and click to place them on the grid. Drag to reposition. Label cities with player names.": "Pilih jenis bangunan dan klik untuk menempatkan di grid. Seret untuk memposisikan ulang. Labeli kota dengan nama pemain.",
    "Screenshot or save your design. Share it with R4/R5 leadership to coordinate the alliance base layout.": "Tangkapan layar atau simpan desain Anda. Bagikan ke kepemimpinan R4/R5 untuk mengkoordinasikan tata letak base aliansi.",
    "Supporter · Ambassador · Booster": "Supporter · Ambassador · Booster",
    "Three steps. One organized fortress.": "Tiga langkah. Satu benteng terorganisir.",
    "Try the Designer": "Coba Desainer",
    "Your alliance base is more than just a flag on a map. It's the difference between holding a position and losing it. A well-designed base channels enemy marches into chokepoints, protects your resource nodes, and ensures reinforcements can reach them in time. Without a layout tool, you're stuck with spreadsheets, hand-drawn maps, or just hoping people put their cities in the right place.": "Base aliansi Anda lebih dari sekedar bendera di peta. Ini perbedaan antara mempertahankan posisi dan kehilangannya. Base yang dirancang baik mengarahkan march musuh ke chokepoint, melindungi node sumber daya, dan memastikan bala bantuan bisa sampai tepat waktu. Tanpa alat tata letak, Anda terjebak dengan spreadsheet, peta gambar tangan, atau hanya berharap orang menaruh kota di tempat yang benar.",
    "Save & load multiple base layouts. Switch between offensive and defensive configurations in seconds.": "Simpan & muat beberapa tata letak base. Beralih antara konfigurasi ofensif dan defensif dalam hitungan detik.",
    "Every city block can be labeled with a player name. When it's time to move, everyone opens the screenshot and knows exactly where to place their city.": "Setiap blok kota bisa dilabeli dengan nama pemain. Saat waktunya pindah, semua orang membuka tangkapan layar dan tahu persis di mana menaruh kota mereka.",
    "Grant up to 2 alliance members in your kingdom access to the Alliance Base Designer.": "Berikan akses Alliance Base Designer ke hingga 2 anggota aliansi di kingdom Anda.",
    "Set your home kingdom in your profile first": "Atur kingdom asal Anda di profil terlebih dahulu",
    "No matching users found": "Tidak ada pengguna yang cocok",
    "Unknown User": "Pengguna Tidak Dikenal",
    "Search by username...": "Cari berdasarkan username...",

    # === battlePlanner (nested) ===
    "Gold Tier kingdom ($100+ Kingdom Fund balance)": "Kingdom Gold Tier (saldo Kingdom Fund $100+)",
    "Gold Tier Required": "Gold Tier Diperlukan",
    "Silver Tier kingdoms (limited-time promo)": "Kingdom Silver Tier (promo waktu terbatas)",
    "Huge shoutout to": "Terima kasih besar untuk",
    "Track active speed buffs per player with live countdown timers. The planner auto-switches between regular and buffed march times.": "Lacak buff kecepatan aktif per pemain dengan timer hitung mundur langsung. Planner otomatis beralih antara waktu march reguler dan buffed.",
    "One-Click Call Orders": "Urutan Panggilan Satu-Klik",
    "Generate the exact call order and copy it to clipboard. Paste it in your alliance chat. Everyone knows when to march.": "Hasilkan urutan panggilan tepat dan salin ke clipboard. Tempel di chat aliansi Anda. Semua tahu kapan march.",
    "Only know one march time? Enter regular or buffed — the planner estimates the other using the ×1.55 ratio. No spreadsheets needed.": "Hanya tahu satu waktu march? Masukkan reguler atau buffed — planner memperkirakan yang lain menggunakan rasio ×1.55. Tanpa spreadsheet.",
    "Save your entire roster — allies and enemies — with their march times. Load them instantly for the next battle. Zero repeated setup.": "Simpan seluruh roster — sekutu dan musuh — dengan waktu march mereka. Muat langsung untuk pertempuran berikutnya. Tanpa pengaturan berulang.",
    "One-click copy of rally call order for Discord": "Salin urutan panggilan rally satu klik untuk Discord",
    "Gantt timeline visualization for every march": "Visualisasi timeline Gantt untuk setiap march",
    "How to Reach Gold Tier": "Cara Mencapai Gold Tier",
    "You have full access as a Gold Tier kingdom member.": "Anda memiliki akses penuh sebagai anggota kingdom Gold Tier.",
    "Available for Gold Tier kingdoms. Contribute to the Kingdom Fund to unlock.": "Tersedia untuk kingdom Gold Tier. Kontribusi ke Kingdom Fund untuk membuka.",
    "Gold Tier": "Gold Tier",
    "KvK BATTLE": "KvK BATTLE",
    "PLANNER": "PLANNER",
    "m": "m",
    "Try It Free": "Coba Gratis",
    "Try the Planner": "Coba Planner",
    "What you get": "Yang Anda dapatkan",
    "Try Battle Planner →": "Coba Battle Planner →",
    "Free access for everyone — try it this weekend's Castle Battle. Coordinate rallies like never before.": "Akses gratis untuk semua — coba di Castle Battle akhir pekan ini. Koordinasikan rally seperti belum pernah sebelumnya.",
    "Free Access": "Akses Gratis",
    "Free for everyone during the trial period. No account required.": "Gratis untuk semua selama masa percobaan. Tanpa akun diperlukan.",

    # === battleRegistry (nested) ===
    "Your Kingdom Has an Active Battle Registry": "Kingdom Anda Memiliki Battle Registry Aktif",
    "Create a Battle Registry for your Silver+ Tier kingdom. Share the link with players so they can register their availability and troop levels for the upcoming castle battle.": "Buat Battle Registry untuk kingdom Silver+ Tier Anda. Bagikan tautan ke pemain agar mereka bisa mendaftar ketersediaan dan level pasukan untuk castle battle mendatang.",
    "GOLD & SILVER TIER KINGDOMS": "KINGDOM GOLD & SILVER TIER",
    "Add Player Manually": "Tambah Pemain Manual",
    "No registrations yet.": "Belum ada registrasi.",
    "Only Editors, Co-Editors, and Battle Managers can create registries. Ask your kingdom leadership for access.": "Hanya Editor, Co-Editor, dan Battle Manager yang bisa membuat registrasi. Minta akses ke kepemimpinan kingdom Anda.",
    "Notes for Players (optional)": "Catatan untuk Pemain (opsional)",
    "Remove entry": "Hapus entri",
    "Only Editors, Co-Editors, and Battle Managers can create registries.": "Hanya Editor, Co-Editor, dan Battle Manager yang bisa membuat registrasi.",
    "Only Silver Tier and above kingdoms can use the KvK Battle Registry.": "Hanya kingdom Silver Tier ke atas yang bisa menggunakan KvK Battle Registry.",
    "For each troop type, select your highest Tier (T8–T11) and Truegold Level (TG0–TG8). Leave blank if you don't use that troop type.": "Untuk setiap jenis pasukan, pilih Tier tertinggi (T8–T11) dan Level Truegold (TG0–TG8). Kosongkan jika Anda tidak menggunakan jenis pasukan itu.",
    "Update Player": "Perbarui Pemain",
    "Auto-filled from your profile.": "Otomatis diisi dari profil Anda.",
    "To": "Ke",

    # === battleRegistryLanding (nested) ===
    "You have full access as a Gold/Silver Tier kingdom member.": "Anda memiliki akses penuh sebagai anggota kingdom Gold/Silver Tier.",
    "You have full access to the Battle Registry.": "Anda memiliki akses penuh ke Battle Registry.",
    "Only your kingdom's players can register. Editors, Co-Editors, and Battle Managers control the registry. Your data stays yours.": "Hanya pemain kingdom Anda yang bisa mendaftar. Editor, Co-Editor, dan Battle Manager mengontrol registrasi. Data Anda tetap milik Anda.",
    "See exactly how many players each alliance is contributing. Hold everyone accountable. Reward the alliances that show up.": "Lihat persis berapa banyak pemain yang dikontribusikan setiap aliansi. Buat semua bertanggung jawab. Beri penghargaan aliansi yang hadir.",
    "Share a single link with your kingdom. Players fill a 30-second form. Username and alliance auto-fill. Zero friction, maximum intel.": "Bagikan satu tautan dengan kingdom Anda. Pemain mengisi formulir 30 detik. Username dan aliansi otomatis terisi. Tanpa gesekan, intelijen maksimal.",
    "Players pick their availability between 12:00–18:00 UTC. Instantly see how many warriors you have at each hour. No more guessing who's online.": "Pemain memilih ketersediaan antara 12:00–18:00 UTC. Langsung lihat berapa banyak prajurit Anda di setiap jam. Tidak perlu menebak siapa yang online.",
    "How to Reach Gold Tier": "Cara Mencapai Gold Tier",
    "Gold & Silver Tier Kingdom Feature": "Fitur Kingdom Gold & Silver Tier",
    "Available for Gold & Silver Tier kingdoms. Contribute to the Kingdom Fund to unlock.": "Tersedia untuk kingdom Gold & Silver Tier. Kontribusi ke Kingdom Fund untuk membuka.",
    "KvK BATTLE": "KvK BATTLE",
    "Share the link. Players fill out their time slot, troop tiers, and truegold levels in 30 seconds.": "Bagikan tautan. Pemain mengisi slot waktu, tier pasukan, dan level truegold dalam 30 detik.",
    "Use the dashboard to see who's available, what they're bringing, and plan your castle hit accordingly.": "Gunakan dasbor untuk melihat siapa yang tersedia, apa yang mereka bawa, dan rencanakan serangan castle sesuai.",
    "View the Registry": "Lihat Registrasi",

    # === botDashboard (nested) ===
    "+ Server": "+ Server",
    "Admin": "Admin",
    "Server already registered.": "Server sudah terdaftar.",
    "Atlas Bot": "Atlas Bot",
    "Auto-post new gift codes": "Auto-post kode hadiah baru",
    "Auto-saves": "Otomatis tersimpan",
    "BLOCK A USER": "BLOKIR PENGGUNA",
    "BLOCKED USERS": "PENGGUNA DIBLOKIR",
    "Set reminder channel.": "Atur channel pengingat.",
    "Working...": "Memproses...",
    "GENERAL SETTINGS": "PENGATURAN UMUM",
    "Get Reminded": "Dapatkan Pengingat",
    "GIFT CODE CHANNEL": "CHANNEL KODE HADIAH",
    "Auto-post new gift codes to your server": "Auto-post kode hadiah baru ke server Anda",
    "How to fix": "Cara memperbaiki",
    "No deployed message to edit.": "Tidak ada pesan yang dideploy untuk diedit.",
    "User has no Discord linked.": "Pengguna tidak memiliki Discord terhubung.",
    "Only the server owner can block users.": "Hanya pemilik server yang bisa memblokir pengguna.",
    "Only the server owner can remove servers.": "Hanya pemilik server yang bisa menghapus server.",
    "Owned by": "Dimiliki oleh",
    "Paste a Discord User ID (18-digit number).": "Tempel ID Pengguna Discord (angka 18 digit).",
    "Preview": "Pratinjau",
    "Reaction Role Panel": "Panel Peran Reaksi",
    "Remove this server?": "Hapus server ini?",
    "Role name": "Nama peran",
    "Save Changes": "Simpan Perubahan",
    "Saved": "Tersimpan",
    "Saving...": "Menyimpan...",
    "Select a server to configure.": "Pilih server untuk dikonfigurasi.",
    "Select server": "Pilih server",
    "Server removed.": "Server dihapus.",
    "Send a DM reminder": "Kirim pengingat DM",
    "Tap an emoji to pick a role": "Ketuk emoji untuk memilih peran",
    "This is the only server you manage.": "Ini satu-satunya server yang Anda kelola.",
    "Update Message": "Perbarui Pesan",
    "User ID": "ID Pengguna",
    "You are the owner": "Anda adalah pemilik",
    "You must deploy first.": "Anda harus deploy terlebih dahulu.",
    "min": "min",

    # === campaign (nested) ===
    "Each qualifying Settler = 1 raffle ticket for their kingdom": "Setiap Settler yang memenuhi syarat = 1 tiket undian untuk kingdom mereka",
    "Prizes drawn live on Discord — smallest to biggest!": "Hadiah diundi langsung di Discord — dari terkecil hingga terbesar!",
    "Real prizes for kingdoms with the most settlers. See campaign details →": "Hadiah nyata untuk kingdom dengan settler terbanyak. Lihat detail kampanye →",

    # === metaAnalysis ===
    "META": "META",

    # === miniKingdomCard ===
    "Battle": "Battle",
    "Prep": "Prep",

    # === referralFunnel ===
    "No referrers yet": "Belum ada perujuk",
    "No users with referral tiers yet": "Belum ada pengguna dengan tier referral",
    "Source": "Sumber",
    "Top Referrers": "Perujuk Teratas",
    "Total Referrals": "Total Referral",

    # === referralIntelligence ===
    "Health Metrics": "Metrik Kesehatan",
    "No referrals yet": "Belum ada referral",
    "No referrers yet": "Belum ada perujuk",
    "No users with referral tiers yet": "Belum ada pengguna dengan tier referral",
    "Source Comparison": "Perbandingan Sumber",
    "Total": "Total",

    # === reportData ===
    "Submissions are reviewed before being applied. False reports may affect your reputation score.": "Pengiriman ditinjau sebelum diterapkan. Laporan palsu bisa mempengaruhi skor reputasi Anda.",
    "Suggested value is same as current value": "Nilai yang disarankan sama dengan nilai saat ini",

    # === reportKvkError ===
    "Win": "Menang",

    # === reviews (nested) ===
    "This kingdom qualifies for Google rich results rating badge": "Kingdom ini memenuhi syarat untuk lencana rating Google rich results",
    "No reviews yet. Be the first to share your experience!": "Belum ada ulasan. Jadilah yang pertama berbagi pengalaman!",
    "Harassment": "Pelecehan",
    "Highest Rated": "Rating Tertinggi",
    "Reviews:": "Ulasan:",
    "Newest": "Terbaru",
    "Write a reply...": "Tulis balasan...",
    "Sending...": "Mengirim...",
    "Showing {{visible}} of {{total}}": "Menampilkan {{visible}} dari {{total}}",
    "Sign in to review": "Masuk untuk mengulas",
    "Sort by:": "Urutkan berdasarkan:",
    "Spam": "Spam",
    "View More": "Lihat Lebih",

    # === scoreBreakdown / scoreMovers ===
    "Score Components": "Komponen Skor",
    "Show {{count}} More": "Tampilkan {{count}} Lagi",

    # === search ===
    "Search by kingdom #...": "Cari berdasarkan kingdom #...",
    "No kingdoms match \"{{query}}\"": "Tidak ada kingdom yang cocok \"{{query}}\"",
    "Search by kingdom number (e.g., 1001)...": "Cari berdasarkan nomor kingdom (mis., 1001)...",

    # === seasons (nested) ===
    "Score history is being calculated. Check back soon.": "Riwayat skor sedang dihitung. Periksa kembali segera.",
    "What is Combined Power Level?": "Apa itu Level Kekuatan Gabungan?",
    "Submissions are closed for this KvK season.": "Pengiriman ditutup untuk musim KvK ini.",
    "Scores reflect each kingdom's Atlas Score before the battle began—based on their track record up to that point. No hindsight, just raw pre-battle power.": "Skor mencerminkan Skor Atlas setiap kingdom sebelum pertempuran dimulai—berdasarkan rekam jejak hingga titik itu. Tanpa melihat ke belakang, hanya kekuatan mentah pra-pertempuran.",
    "Score Timing": "Waktu Skor",
    "Select a season": "Pilih musim",

    # === share (nested) ===
    "Get Embed Code": "Dapatkan Kode Embed",
    "Scan to open on mobile": "Pindai untuk buka di mobile",
    "Share Image": "Bagikan Gambar",
    "Share...": "Bagikan...",
    "Share {{type}}": "Bagikan {{type}}",
    "Shared!": "Dibagikan!",
    "Sharing...": "Membagikan...",
    "Show QR Code": "Tampilkan Kode QR",

    # === similarKingdoms ===
    "How it works": "Cara kerjanya",
    "Nearby Kingdoms": "Kingdom Terdekat",

    # === simulator (nested) ===
    "See how wins and losses affect your score": "Lihat bagaimana kemenangan dan kekalahan mempengaruhi skor Anda",
    "Understand the scoring formula": "Pahami rumus penilaian",
    "Form Bonus": "Bonus Kondisi",
    "See how your next KvK results could change your Atlas Score": "Lihat bagaimana hasil KvK berikutnya bisa mengubah Skor Atlas Anda",
    "Reset": "Reset",
    "Sign in to unlock the Score Simulator": "Masuk untuk membuka Simulator Skor",
    "Simulate Next KvK": "Simulasikan KvK Berikutnya",
    "Streak Impact": "Dampak Streak",
    "Unlock Simulator": "Buka Simulator",

    # === support (nested) ===
    "Not everyone can donate, and that's totally fine! Here's how you can still help:": "Tidak semua orang bisa berdonasi, dan itu tidak masalah! Begini cara Anda tetap bisa membantu:",
    "Full KvK History": "Riwayat KvK Lengkap",
    "See where every kingdom stands": "Lihat posisi setiap kingdom",
    "Full stats and performance history": "Statistik lengkap dan riwayat performa",
    "Transfer Hub": "Transfer Hub",
    "Atlas Discord Bot": "Atlas Discord Bot",
    "Want to give more? You can increase your amount in the Stripe portal after subscribing.": "Ingin memberi lebih? Anda bisa menambah jumlah di portal Stripe setelah berlangganan.",
    "Note: One-time donations don't include the Supporter badge or Discord role.": "Catatan: Donasi satu kali tidak termasuk lencana Supporter atau peran Discord.",
    "Full access to the Rally Coordinator — plan rallies, track marches, coordinate hits": "Akses penuh ke Rally Coordinator — rencanakan rally, lacak march, koordinasikan serangan",
    "Unlimited /multirally and premium Discord bot commands (free: 5/day)": "/multirally tak terbatas dan perintah bot Discord premium (gratis: 5/hari)",
    "Unlimited Bot Commands": "Perintah Bot Tak Terbatas",
    "First to try new features before public release": "Pertama mencoba fitur baru sebelum rilis publik",
    "Gift Code Bulk Redeem": "Redeem Massal Kode Hadiah",
    "Atlas Supporter": "Atlas Supporter",

    # === table ===
    "Show Columns": "Tampilkan Kolom",

    # === tiers ===
    "S Tier - Elite (Top 10%)": "S Tier - Elite (Top 10%)",

    # === toolDelegates ===
    "Search by username...": "Cari berdasarkan username...",

    # === tools (nested) ===
    "Atlas Discord Bot": "Atlas Discord Bot",
    "We're building what the community needs. Drop your suggestions in Discord.": "Kami membangun apa yang dibutuhkan komunitas. Kirimkan saran Anda di Discord.",
    "Time your rallies to land together. Set hit order, march times, and delay windows — so your alliance strikes as one.": "Atur timing rally agar mendarat bersamaan. Atur urutan serangan, waktu march, dan jendela delay — agar aliansi Anda menyerang sebagai satu kesatuan.",
    "Find your next kingdom — or find the right players. Browse listings, create a transfer profile, and apply directly. No more blind transfers.": "Temukan kingdom berikutnya — atau temukan pemain yang tepat. Jelajahi daftar, buat profil transfer, dan lamar langsung. Tidak ada lagi transfer buta.",

    # === transferHub (nested) ===
    "Bio": "Bio",
    "Select \"I'm Transferring\" from the toggle at the top. This unlocks tools built for you.": "Pilih \"Saya Transfer\" dari toggle di atas. Ini membuka alat yang dibangun untuk Anda.",
    "Set your power, TC level, language, and what you're looking for. Kingdoms see this when you apply.": "Atur kekuatan, level TC, bahasa, dan apa yang Anda cari. Kingdom melihat ini saat Anda melamar.",
    "Create your Transfer Profile": "Buat Profil Transfer Anda",
    "Found the right one? Hit Apply. You can have up to 3 active applications. Track their status in My Applications.": "Menemukan yang tepat? Klik Lamar. Anda bisa memiliki hingga 3 lamaran aktif. Lacak statusnya di Lamaran Saya.",
    "Open the Recruiter Dashboard. Add your pitch, requirements, languages, vibe tags, and event times. This is your kingdom's storefront.": "Buka Dasbor Perekrut. Tambahkan pitch, persyaratan, bahasa, tag suasana, dan waktu event. Ini adalah etalase kingdom Anda.",
    "Set up your listing": "Atur daftar Anda",
    "Fund your listing (optional)": "Danai daftar Anda (opsional)",
    "To recruit for your kingdom, you need to link your in-game account first. This tells us which kingdom you represent.": "Untuk merekrut untuk kingdom Anda, Anda perlu menghubungkan akun in-game terlebih dahulu. Ini memberi tahu kami kingdom mana yang Anda wakili.",
    "Sign in and link your Kingshot account to claim your kingdom, set up your listing, and review transfer applications.": "Masuk dan hubungkan akun Kingshot untuk klaim kingdom, atur daftar, dan tinjau lamaran transfer.",
    "Sign in to endorse this candidate.": "Masuk untuk mendukung kandidat ini.",

    # === transferHubLanding (nested) ===
    "Whether you're looking for a new home or looking for strong players — the Transfer Hub connects you with the right match. No cost, no catch.": "Apakah Anda mencari rumah baru atau mencari pemain kuat — Transfer Hub menghubungkan Anda dengan kecocokan yang tepat. Tanpa biaya, tanpa jebakan.",
    "Optionally deposit into your kingdom's fund to unlock priority placement, invite features, and a premium badge. Anyone in your kingdom can contribute.": "Opsional deposit ke dana kingdom Anda untuk membuka penempatan prioritas, fitur undangan, dan lencana premium. Siapa pun di kingdom Anda bisa berkontribusi.",
    "See which kingdoms are actively recruiting — with Atlas Scores, KvK records, and community reviews. No more guessing.": "Lihat kingdom mana yang aktif merekrut — dengan Skor Atlas, catatan KvK, dan ulasan komunitas. Tidak perlu menebak lagi.",

    # === transferProfile (nested) ===
    "Recruiters will see your username and kingdom of origin.": "Perekrut akan melihat username dan kingdom asal Anda.",

    # === upgrade (nested) ===
    "Supporter": "Supporter",

    # === prepScheduler remaining ===
    "Instructions or any reminders...": "Instruksi atau pengingat apa pun...",
    "Confirm unlock?": "Konfirmasi buka kunci?",
    "Construction": "Konstruksi",
    "Research": "Riset",
    "Training": "Pelatihan",
    "General": "Umum",
    "Day 1": "Hari 1",
    "Day 2": "Hari 2",
    "Day 3": "Hari 3",
    "Mon": "Sen",
    "Wed": "Rab",
    "Fri": "Jum",
    "Sat": "Sab",
    "Sun": "Min",
    "Deadline": "Tenggat Waktu",
    "Export CSV": "Ekspor CSV",
    "Lock Schedule": "Kunci Jadwal",
    "Unlock Schedule": "Buka Kunci Jadwal",
    "Notify Unsubmitted": "Beritahu Belum Mengirim",
    "Submissions": "Pengiriman",
    "Assigned": "Ditetapkan",
    "Waitlisted": "Daftar Tunggu",
    "Unassigned": "Belum Ditetapkan",
    "Override": "Ganti",
    "Clear All": "Hapus Semua",
    "Opt-Out": "Tidak Ikut",
    "Opted Out": "Tidak Ikut",
    "Your Submission": "Pengiriman Anda",
    "Edit Submission": "Edit Pengiriman",
    "Submit Availability": "Kirim Ketersediaan",
    "Speedup Type": "Jenis Speedup",
    "Amount": "Jumlah",
    "Proof Screenshot": "Tangkapan Layar Bukti",
    "Alliance (3 chars)": "Aliansi (3 karakter)",
    "Schedule created!": "Jadwal dibuat!",
    "Schedule archived.": "Jadwal diarsipkan.",
    "Schedule deleted.": "Jadwal dihapus.",
    "Schedule locked.": "Jadwal dikunci.",
    "Schedule unlocked.": "Jadwal dibuka.",
    "Submission saved!": "Pengiriman tersimpan!",
    "Slot assigned.": "Slot ditetapkan.",
    "Auto-assign complete.": "Auto-assign selesai.",
    "Assignments cleared.": "Penugasan dihapus.",
    "Opt-outs updated.": "Opt-out diperbarui.",
    "Day settings updated.": "Pengaturan hari diperbarui.",
    "Deadline updated.": "Tenggat waktu diperbarui.",
    "Lock status updated.": "Status kunci diperbarui.",
    "Notifications sent!": "Notifikasi terkirim!",
    "Change request submitted.": "Permintaan perubahan dikirim.",
    "Change request approved.": "Permintaan perubahan disetujui.",
    "Change request declined.": "Permintaan perubahan ditolak.",
    "Player entry updated.": "Entri pemain diperbarui.",
    "Player entry deleted.": "Entri pemain dihapus.",
    "Manager added.": "Manajer ditambahkan.",
    "Manager removed.": "Manajer dihapus.",
    "Stagger toggled.": "Stagger diubah.",
    "Status updated.": "Status diperbarui.",
    "Form closed.": "Formulir ditutup.",
    "Form reopened.": "Formulir dibuka kembali.",

    # === recruiter remaining ===
    "Active Listings": "Daftar Aktif",
    "All Applications": "Semua Lamaran",
    "Inbox": "Kotak Masuk",
    "Kingdom Profile": "Profil Kingdom",
    "Listing Settings": "Pengaturan Daftar",
    "Recruiter Dashboard": "Dasbor Perekrut",

    # === admin remaining ===
    "Admin access": "Akses admin",
    "Admin Panel": "Panel Admin",
    "Approve": "Setujui",
    "Decline": "Tolak",
    "Delete": "Hapus",
    "Pending": "Tertunda",
    "Rejected": "Ditolak",
    "Approved": "Disetujui",
    "Processing": "Memproses",
}
