# Bandit Security Scanner Configuration
# Suppress known low-severity findings that are false positives in this codebase
#
# B110: try_except_pass — Used intentionally for graceful fallbacks in API handlers
# B105: hardcoded_password_string — False positive on auth scheme strings like 'bearer'

skips:
  - B110
  - B105
